"""
cot_met_explain_ethics.py
==========================
ExplainEthics adaptation of main/argos/cot_met_clutrr.py.

Purpose
-------
This is the main reasoning loop for running the ARGOS/SAT-LM pipeline on
the ExplainEthics dataset. It mirrors cot_met_clutrr.py structurally but
adapts every domain-specific part for moral reasoning:

  - Dataset: hard_question.json instead of clutrr_test.json
  - Variable names: propositional implies() predicates instead of kinship relations
  - Labels: moral norms (violate_care, etc.) instead of family relations
  - Question format: "Does [context] violate [norm]?" instead of "Is X Y's relation?"
  - Backbone variable extraction: predicate names instead of person name pairs

Pipeline flow (same as cot_met_clutrr.py):
  1. Load dimacs/ SAT files generated by explain_ethics_to_sat.py
  2. Get backbone (get_bb) → set of literals that hold across all SAT solutions
  3. Run next_var() loop:
     a. Extract unresolved backbone literals → moral predicate candidates
     b. Ask LLM to generate an implies() rule connecting the candidates
     c. Add the rule to the SAT formula and re-extract the backbone
     d. If the backbone becomes conclusive, report True/False
     e. If the loop limit is reached, fall back to Chain-of-Thought (cot())
  4. Compare prediction vs ground-truth labels; compute accuracy

# >>> [ExplainEthics Adaptation] BEGIN: Module
"""

import os
import shutil
import numpy as np
import time
import json
import random
from dotenv import load_dotenv

# Load .env for HF_TOKEN etc.
load_dotenv()

import torch
from torch.utils.data import DataLoader

# All paths are relative to the WSL mount of the Windows project directory
USER_PATH = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/'

# All recognised moral norm labels in the ExplainEthics dataset.
# Used by cot() and next_var() to pick the best norm rather than
# confirming/denying the (potentially decoy) label shown per example.
_MORAL_NORMS = [
    "violate_care", "violate_fairness", "violate_loyalty",
    "violate_authority", "violate_sanctity", "violate_liberty",
]

os.environ["CURL_CA_BUNDLE"] = ""
os.environ["REQUESTS_CA_BUNDLE"] = ""
cache_dir = os.path.join(os.getcwd(), '.cache/huggingface/hub')
os.environ['TRANSFORMERS_CACHE'] = cache_dir
os.environ['HF_HOME'] = cache_dir

import pickle as pkl
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import argparse
from tqdm import tqdm
import time
import datetime
import warnings
import contextlib
import requests
from urllib3.exceptions import InsecureRequestWarning

# ---------------------------------------------------------------------------
# SSL verification bypass (same as cot_met_clutrr.py) to handle internal proxy
# ---------------------------------------------------------------------------
old_merge_environment_settings = requests.Session.merge_environment_settings

@contextlib.contextmanager
def no_ssl_verification():
    opened_adapters = set()

    def merge_environment_settings(self, url, proxies, stream, verify, cert):
        opened_adapters.add(self.get_adapter(url))
        settings = old_merge_environment_settings(self, url, proxies, stream, verify, cert)
        settings['verify'] = False
        return settings

    requests.Session.merge_environment_settings = merge_environment_settings
    try:
        with warnings.catch_warnings():
            warnings.simplefilter('ignore', InsecureRequestWarning)
            yield
    finally:
        requests.Session.merge_environment_settings = old_merge_environment_settings
        for adapter in opened_adapters:
            try:
                adapter.close()
            except:
                pass


class Struct:
    """Simple namespace class to convert dicts to attribute-accessible objects."""
    def __init__(self, **entries):
        self.__dict__.update(entries)


# ---------------------------------------------------------------------------
# LLM wrapper — identical to cot_met_clutrr.py; kept self-contained here
# so this file can be run without importing cot_met_clutrr.py
# ---------------------------------------------------------------------------
class LLM():
    """
    Thin wrapper around a HuggingFace causal LM.
    Provides sentence probability scoring (for NLI-style yes/no), completion,
    and yes/no prediction helpers (yn).
    """
    def __init__(self, args):
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype="bfloat16",
            bnb_4bit_use_double_quant=True,
        )
        with no_ssl_verification():
            self.tokenizer = AutoTokenizer.from_pretrained(
                args.engine,
                cache_dir=cache_dir,
                token=os.getenv("HF_TOKEN"),
                trust_remote_code=False
            )
            self.tokenizer.pad_token = self.tokenizer.eos_token
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
            self.tokenizer.padding_side = "left"

            self.model = AutoModelForCausalLM.from_pretrained(
                args.engine,
                cache_dir=cache_dir,
                quantization_config=quant_config,
                device_map='auto',
                token=os.getenv("HF_TOKEN"),
                attn_implementation="sdpa",
                trust_remote_code=False
            )
            self.model.config.use_cache = True

    @property
    def device(self):
        return next(self.model.parameters()).device

    _kv_cache_reported = False

    # def sentence_probabilities(self, sentences):
    #     """Return log-probabilities for each sentence (used for NLI scoring)."""
    #     with torch.no_grad():
    #         sentence_tokens = self.tokenizer(sentences, return_tensors='pt', padding=True)
    #         sentence_token_ids = sentence_tokens.input_ids.to(self.device)
    #         attention_mask = sentence_tokens.attention_mask.to(self.device)

    #         first_different_token = (
    #             sentence_token_ids == sentence_token_ids[0, :].unsqueeze(0)
    #         ).all(dim=0).long().argmin()
    #         common_prefix = sentence_token_ids[0, :first_different_token].unsqueeze(0)
    #         common_prefix_output = self.model(common_prefix, use_cache=True)
    #         pkv = common_prefix_output.past_key_values

    #         expanded_pkv = None
    #         try:
    #             from transformers.cache_utils import DynamicCache
    #             import transformers
    #             transformers_version = tuple(int(x) for x in transformers.__version__.split(".")[:2])

    #             if isinstance(pkv, DynamicCache):
    #                 if transformers_version >= (4, 43):
    #                     # New API: key_cache / value_cache lists
    #                     if pkv.key_cache and all(k is not None and v is not None
    #                             for k, v in zip(pkv.key_cache, pkv.value_cache)):
    #                         new_cache = DynamicCache()
    #                         for k, v in zip(pkv.key_cache, pkv.value_cache):
    #                             new_cache.key_cache.append(k.expand(len(sentences), -1, -1, -1).contiguous())
    #                             new_cache.value_cache.append(v.expand(len(sentences), -1, -1, -1).contiguous())
    #                         expanded_pkv = new_cache
    #                 else:
    #                     # Old API: iterate over layers directly as (key, value) tuples
    #                     layers = list(pkv)
    #                     if layers and all(t is not None for layer in layers for t in layer):
    #                         expanded_pkv = tuple(
    #                             tuple(t.expand(len(sentences), -1, -1, -1).contiguous() for t in layer)
    #                             for layer in layers
    #                         )
    #             elif pkv is not None:
    #                 # Legacy pure tuple-of-tuples format
    #                 if all(t is not None for layer in pkv for t in layer):
    #                     expanded_pkv = tuple(
    #                         tuple(t.expand(len(sentences), -1, -1, -1).contiguous() for t in layer)
    #                         for layer in pkv
    #                     )
    #         except Exception as e:
    #             print(f'KV-cache expansion failed: {e}')
    #             expanded_pkv = None

    #         if expanded_pkv is not None:
    #             if not LLM._kv_cache_reported:
    #                 print(f"[KV-cache] ACTIVE — {type(pkv).__name__}")
    #                 LLM._kv_cache_reported = True
    #             rest_outputs = self.model(
    #                 sentence_token_ids[:, first_different_token:],
    #                 past_key_values=expanded_pkv
    #             )
    #             logits = torch.concat(
    #                 [common_prefix_output.logits.expand(len(sentences), -1, -1), rest_outputs.logits],
    #                 dim=1
    #             ).to(self.device)
    #         else:
    #             if not LLM._kv_cache_reported:
    #                 print(f"[KV-cache] DISABLED — slow path")
    #                 LLM._kv_cache_reported = True
    #             full_outputs = self.model(sentence_token_ids, attention_mask=attention_mask)
    #             logits = full_outputs.logits.to(self.device)

    #         log_probs = logits.log_softmax(-1)
    #         log_probs = log_probs[:, :-1, :].gather(
    #             2, sentence_token_ids[:, 1:][:, :, None]
    #         ).squeeze(-1).to(self.device)
    #         log_probs = (log_probs * attention_mask[:, 1:]).sum(-1).cpu()
    #     return log_probs

    def sentence_probabilities(self, sentences):
        """Return log-probabilities for each sentence (used for NLI scoring)."""
        with torch.no_grad():
            sentence_tokens = self.tokenizer(sentences, return_tensors='pt', padding=True)
            sentence_token_ids = sentence_tokens.input_ids.to(self.device)
            attention_mask = sentence_tokens.attention_mask.to(self.device)

            first_different_token = (
                sentence_token_ids == sentence_token_ids[0, :].unsqueeze(0)
            ).all(dim=0).long().argmin()
            common_prefix = sentence_token_ids[0, :first_different_token].unsqueeze(0)
            common_prefix_output = self.model(common_prefix, use_cache=True)
            pkv = common_prefix_output.past_key_values

            # Properly expand KV cache for batch processing
            expanded_pkv = None
            batch_size = len(sentences)

            if pkv is not None:
                try:
                    from transformers.cache_utils import DynamicCache

                    if isinstance(pkv, DynamicCache):
                        # DynamicCache: expand key_cache and value_cache
                        expanded_pkv = DynamicCache()
                        for k, v in zip(pkv.key_cache, pkv.value_cache):
                            if k is not None and v is not None:
                                # Expand to match batch size: (batch, num_heads, seq_len, head_dim)
                                expanded_k = k.expand(batch_size, -1, -1, -1).contiguous()
                                expanded_v = v.expand(batch_size, -1, -1, -1).contiguous()
                                expanded_pkv.key_cache.append(expanded_k)
                                expanded_pkv.value_cache.append(expanded_v)
                            else:
                                expanded_pkv.key_cache.append(None)
                                expanded_pkv.value_cache.append(None)
                    else:
                        # Legacy tuple format: expand each layer's (key, value) tensors
                        expanded_pkv = []
                        for layer_cache in pkv:
                            if isinstance(layer_cache, tuple) and len(layer_cache) == 2:
                                k, v = layer_cache
                                if k is not None and v is not None:
                                    expanded_k = k.expand(batch_size, -1, -1, -1).contiguous()
                                    expanded_v = v.expand(batch_size, -1, -1, -1).contiguous()
                                    expanded_pkv.append((expanded_k, expanded_v))
                                else:
                                    expanded_pkv.append(layer_cache)
                            else:
                                expanded_pkv.append(layer_cache)
                        expanded_pkv = tuple(expanded_pkv)

                except Exception as e:
                    print(f'KV-cache expansion failed: {e}')
                    expanded_pkv = None

            if expanded_pkv is not None:
                if not LLM._kv_cache_reported:
                    print(f"[KV-cache] ACTIVE — {type(pkv).__name__}")
                    LLM._kv_cache_reported = True
                rest_outputs = self.model(
                    sentence_token_ids[:, first_different_token:],
                    past_key_values=expanded_pkv
                )
                logits = torch.concat(
                    [common_prefix_output.logits.expand(batch_size, -1, -1), rest_outputs.logits],
                    dim=1
                ).to(self.device)
            else:
                if not LLM._kv_cache_reported:
                    print(f"[KV-cache] DISABLED — slow path")
                    LLM._kv_cache_reported = True
                full_outputs = self.model(sentence_token_ids, attention_mask=attention_mask)
                logits = full_outputs.logits.to(self.device)

            log_probs = logits.log_softmax(-1)
            log_probs = log_probs[:, :-1, :].gather(
                2, sentence_token_ids[:, 1:][:, :, None]
            ).squeeze(-1).to(self.device)
            log_probs = (log_probs * attention_mask[:, 1:]).sum(-1).cpu()
        return log_probs

    def nli(self, sentences, unknown):
        """Score True/False (or True/Unknown/False) probabilities for a sentence."""
        if unknown:
            true_probs, maybe_probs, false_probs = self.sentence_probabilities(
                [sentences + "(A)", sentences + "(B)", sentences + "(C)"]
            )
            return {'True': true_probs, 'Maybe': maybe_probs, 'False': false_probs}
        else:
            true_probs, false_probs = self.sentence_probabilities(
                [sentences + "(A)", sentences + "(B)"]
            )
            return {'True': true_probs, 'False': false_probs}

    def yn(self, sentences, norm=True, relaxed=False, obvious=False, unknown=False, fewshot=None, maybe=False):
        """
        Batch yes/no (or yes/maybe/no) predictions via log-probability scoring.
        Returns a list of probability tensors.
        """
        yns = []
        for sentence in sentences:
            if fewshot:
                sentence = fewshot + sentence
            if maybe:
                yns += [sentence + "Yes", sentence + "Maybe", sentence + "No"]
            elif unknown:
                yns += [sentence + "True", sentence + "Unknown", sentence + "False"]
            else:
                yns += [sentence + "Yes", sentence + "No"]
        probs = []
        batch_size = 256
        for i in range(0, len(yns), batch_size):
            probs += list(self.sentence_probabilities(yns[i:i + batch_size]))
        probs = torch.tensor(probs)
        pyes, pno, pmaybe = [], [], []
        z = 3 if (maybe or unknown) else 2
        for i in range(0, len(probs), z):
            if maybe or unknown:
                yes, mb, no = probs[i], probs[i + 1], probs[i + 2]
            else:
                yes, no = probs[i], probs[i + 1]
            if norm:
                if maybe or unknown:
                    y, m, n = torch.tensor([yes, mb, no]).softmax(-1)
                else:
                    y, n = torch.tensor([yes, no]).softmax(-1)
                pyes.append(y)
                pno.append(n)
                if maybe or unknown:
                    pmaybe.append(m)
            else:
                pyes.append(1 - yes / (yes + no))
        if maybe:
            return torch.stack([torch.tensor(pyes), torch.tensor(pmaybe), torch.tensor(pno)])
        if unknown:
            return [torch.tensor(pyes), torch.tensor(pmaybe), torch.tensor(pno)]
        return [torch.tensor(pyes), torch.tensor(pno)]

    def complete(self, prompt, max_new=25, temp=1, topk=0, max_length=300):
        """Generate a continuation for a given prompt string."""
        encoded = self.tokenizer(
            prompt,
            return_tensors='pt',
            padding=True,
            truncation=True,
            max_length=max_length
        )
        encode_ids = encoded.input_ids.to(self.device)
        attn_mask = encoded.attention_mask.to(self.device)
        generated_outputs = self.model.generate(
            encode_ids,
            attention_mask=attn_mask,
            pad_token_id=self.tokenizer.eos_token_id,
            max_new_tokens=max_new,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=(temp > 0 and topk > 0),
            temperature=temp if (temp > 0 and topk > 0) else None,
            top_k=topk if topk > 0 else None,
        )
        responses = self.tokenizer.batch_decode(
            generated_outputs.sequences,
            skip_special_tokens=True
        )
        return responses


# ---------------------------------------------------------------------------
# SAT formula helpers — identical to cot_met_clutrr.py; no domain changes needed
# >>> [ExplainEthics Adaptation] BEGIN: add_clause / add_var
# ---------------------------------------------------------------------------
def add_clause(file):
    """
    Increment the clause count in the DIMACS header by 1.
    Called before appending a new blocking clause to a .cnf file.
    """
    f = open(file, 'r')
    lines = f.readlines()
    writestr = ''
    for line in lines:
        if line.startswith('p cnf'):
            num_var, num_clause = line.split(' ')[2], line.split(' ')[3]
            writestr += 'p cnf ' + str(num_var) + ' ' + str(int(num_clause) + 1) + '\n'
        else:
            writestr += line
    f.close()
    f = open(file, 'w')
    f.write(writestr)
    f.close()


def add_var(file):
    """Increment the variable count in the DIMACS header by 1."""
    f = open(file, 'r')
    lines = f.readlines()
    writestr = ''
    for line in lines:
        if line.startswith('p cnf'):
            num_var, num_clause = line.split(' ')[2], line.split(' ')[3]
            writestr += 'p cnf ' + str(int(num_var) + 1) + ' ' + str(int(num_clause)) + '\n'
        else:
            writestr += line
    f.close()
    f = open(file, 'w')
    f.write(writestr)
    f.close()
# <<< [ExplainEthics Adaptation] END: add_clause / add_var


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: rule_check
# Gate that validates an inferred implication rule before it is written to
# the SAT formula. Mirrors cot_met_pronto.rule_check() but uses ethics-
# specific few-shot examples.
# ---------------------------------------------------------------------------
def rule_check(rule, contra_thresh=0, context_thresh=0, prob='', llm=None):
    """
    Returns (accepted: bool, scores: [contra_score, context_score]).

    Two independent checks:
      a) Non-contradiction: the rule must not be logically contradictory.
      b) Contextual relevance: the rule must be relevant to the story context.
    """
    # --- (a) Non-contradiction check ---
    contra_fs = (
        'Does the following ethical rule seem contradictory?\n'
        'Rule: tearing_down_decorations implies emotional_harm.\n'
        'Answer: \\box{ No } this does not seem contradictory. '
        'Tearing down something someone cared about causes emotional harm.\n'
        'Does the following ethical rule seem contradictory?\n'
        'Rule: helping_a_friend implies violate_loyalty.\n'
        'Answer: \\box{ Yes } this seems contradictory. Helping a friend strengthens loyalty, not violates it.\n'
    )
    contra_prompt = (
        contra_fs
        + 'Does the following ethical rule seem contradictory?\n'
        + 'Rule: ' + rule + '\n'
        + 'Answer: \\box{ '
    )
    # yn returns [p_yes, p_no]; p_yes here = P("Yes, contradictory")
    # We want P(NOT contradictory) = 1 - p_yes
    a = 1 - llm.yn([contra_prompt])[0]

    # --- (b) Contextual relevance check ---
    context_str = prob.get('context', '') if isinstance(prob, dict) else str(prob)
    context_prompt = (
        'Here is the story context:\n'
        + context_str + '\n'
        + 'Does the following new ethical rule seem contextually relevant to this story?\n'
        + 'Rule: ' + rule + '\n'
        + 'Answer "Yes" or "No": '
    )
    b = llm.yn([context_prompt])[0]  # P("Yes, relevant")

    if a < contra_thresh:
        print(f'[rule_check] REJECTED by contradiction: {rule!r}  (score={a:.3f})')
        return False, [a, b]
    if b < context_thresh:
        print(f'[rule_check] REJECTED by context:       {rule!r}  (score={b:.3f})')
        return False, [a, b]

    print(f'[rule_check] ACCEPTED: {rule!r}  (contra={a:.3f}, context={b:.3f})')
    return True, [a, b]
# <<< [ExplainEthics Adaptation] END: rule_check


# ---------------------------------------------------------------------------
# get_sol — faithful copy from cot_met_clutrr.py.
# Runs CaDiCaL on pos/neg CNF files and collects satisfying solutions.
# Returns {'pos': [solutions], 'neg': [solutions]}.
# An empty list for either polarity means that formula is UNSATISFIABLE,
# which is exactly the paper's termination criterion:
#   len(new_sols['pos']) == 0  →  pos formula UNSAT  →  (P∧C) ⊢ ¬Q
#   len(new_sols['neg']) == 0  →  neg formula UNSAT  →  (P∧C) ⊢ Q
# ---------------------------------------------------------------------------
def get_sol(file, lim=10000, del_sols=None, seedrun=0):
    solutions = {'pos': [], 'neg': []}
    files = [
        '/'.join(file.split('/')[:-1]) + '/pos_' + file.split('/')[-1],
        '/'.join(file.split('/')[:-1]) + '/neg_' + file.split('/')[-1]
    ]
    for i in range(len(files)):
        cur_file = files[i]
        shutil.copy(
            cur_file,
            '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
        )
        if del_sols is not None:
            polarity = 'pos' if 'pos' in cur_file and 'neg' not in cur_file else 'neg'
            ds = del_sols[polarity]
            for sol in ds:
                add_clause(
                    '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
                )
                cf = open(
                    '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1], 'a'
                )
                write_str = '\n'
                for lit in sol:
                    write_str += str(-lit) + ' '
                cf.write(write_str)
                cf.close()
        count = 0
        while True:
            count += 1
            if count > lim:
                break
            log_pth = (
                '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/'
                + cur_file.split('/')[-1][:-4] + '.log'
            )
            print(f'[get_sol] Running CaDiCaL, log: {log_pth}')
            os.system(
                USER_PATH + '/sat_gen/sat_tools/postprocess/cadical/build/cadical '
                + '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/'
                + cur_file.split('/')[-1] + '> ' + log_pth
            )
            cf = open(log_pth, 'r')
            lines = cf.readlines()
            el = lines[-1]
            print(f'[get_sol] exit line: {el.strip()}')
            try:
                ec = el.split('exit ')[1].strip('\n')
            except Exception:
                print(f'[get_sol] Could not parse exit code from: {el!r}')
                break
            if ec == '20':
                print('[get_sol] UNSATISFIABLE (exit 20)')
                break
            sl = lines[1:]
            while not sl[0].startswith('s '):
                sl = sl[1:]
            sl = sl[1:]
            solution = []
            while sl[0].startswith('v '):
                solution += list(map(int, sl[0].strip('\n').split(' ')[1:]))
                sl = sl[1:]
            if 'pos' in cur_file and 'neg' not in cur_file:
                solutions['pos'].append(solution)
            elif 'neg' in cur_file:
                solutions['neg'].append(solution)
            cf.close()
            add_clause(
                '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
            )
            cf = open(
                '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1], 'a'
            )
            write_str = '\n'
            for lit in solution:
                write_str += str(-lit) + ' '
            cf.write(write_str)
            cf.close()
    return solutions


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: get_bb (backbone extraction)
# Backbone extraction — calls the CadiBack binary to find literals common to
# all SAT solutions. Identical mechanics to cot_met_clutrr.py.
# ---------------------------------------------------------------------------
def get_bb(file, del_sols=None, seedrun=0):
    """
    Run CadiBack on pos and neg polarity CNF files and return the backbone.
    The backbone is the set of literals that have the same truth value in ALL
    satisfying assignments — i.e. the things that MUST be true/false.

    Returns dict {'pos': [literals], 'neg': [literals]}.
    """
    bb = {'pos': [], 'neg': []}
    files = [
        '/'.join(file.split('/')[:-1]) + '/pos_' + file.split('/')[-1],
        '/'.join(file.split('/')[:-1]) + '/neg_' + file.split('/')[-1]
    ]
    for i in range(len(files)):
        cur_file = files[i]
        # Copy to tempfiles dir for isolated solver runs
        shutil.copy(
            cur_file,
            '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
        )

        if del_sols is not None:
            # Block previously seen solutions by adding their negations as clauses
            polarity = 'pos' if 'pos' in cur_file and 'neg' not in cur_file else 'neg'
            ds = del_sols[polarity]
            for sol in ds:
                add_clause(
                    '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
                )
                cf = open(
                    '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1], 'a'
                )
                write_str = '\n'
                for lit in sol:
                    write_str += str(-lit) + ' '
                cf.write(write_str)
                cf.close()

        # Run CadiBack to extract the backbone
        print('running cadiback for explain_ethics backbone extraction')
        bbone_pth = (
            '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/'
            + cur_file.split('/')[-1][:-4] + ".bbone"
        )
        print(f"[get_bb] Writing backbone to: {bbone_pth}")
        os.system(
            "timeout 5000 " + USER_PATH + "/main/cadiback/cadiback "
            + '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/'
            + cur_file.split('/')[-1] + '> ' + bbone_pth
        )

        try:
            bbone_f = open(bbone_pth, 'r')
            lines = bbone_f.readlines()
        except Exception as e:
            print(f"[get_bb] Failed to open bbone file: {e}")
            # breakpoint()
            continue
        for line in lines:
            if line.startswith('b'):
                # 'b' lines contain the backbone literals as space-separated integers
                lits = line.split(' ')[1:]
                for lit in lits:
                    lit = lit.strip()
                    if lit == '0':
                        continue
                    lit = int(lit)
                    if 'pos' in cur_file and 'neg' not in cur_file:
                        bb['pos'].append(lit)
                    elif 'neg' in cur_file:
                        bb['neg'].append(lit)

    return bb
# <<< [ExplainEthics Adaptation] END: get_bb


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: cot() function for ethics
# Chain-of-Thought fallback reasoning for moral norm classification.
# Unlike CLUTRR (which asks "Is X Y's relation?"), we ask "Does this scenario
# violate [norm]?" using ethical few-shot examples.
# ---------------------------------------------------------------------------
def cot(prob, n=5):
    """
    Run Chain-of-Thought moral reasoning as a fallback when the backbone loop
    cannot converge within the loop limit.

    Instead of asking "Does this violate [shown label]?" (which is biased by
    decoy labels), we now ask the model to choose which norm from _MORAL_NORMS
    is MOST violated. The predicted norm is then matched against the ground-truth
    label to produce a true/false vote.

    Returns (votes: Tensor[2], prompts: list[str])
      votes[0] > votes[1]  → prediction is 'true'  (chosen norm matches label)
      votes[1] > votes[0]  → prediction is 'false' (chosen norm does not match)
    """
    # >>> [ExplainEthics Adaptation] BEGIN: multi-class norm selection prompt
    # Few-shot examples that demonstrate norm identification without anchoring
    # on the shown label — model must choose from the full set of _MORAL_NORMS.
    norms_list_str = ", ".join(_MORAL_NORMS)
    few_shot = (
        f"The possible moral norm violations are: {norms_list_str}.\n"
        "Context: I crush the frog. "
        # f"Question: Does this violate violate_care? Of these norm violations, which one does this action most violate? "
        f"Question: Does this violate violate_care? "
        # f"Question: Of these norm violations, which one does this action most violate? "
        "Answer: Let's think step by step. "
        "1. Frogs are animals. 2. Crushing causes physical harm to an animal. "
        "3. Causing harm to a living being violates the norm of care. "
        "Therefore the answer is violate_care.\n"
        "Context: I won my match by moving my ball when the other player wasn't looking. "
        # f"Question: Does this violate violate_fairness? Of these norm violations, which one does this action most violate? "
        f"Question: Does this violate violate_fairness? "
        # f"Question: Of these norm violations, which one does this action most violate? "
        "Answer: Let's think step by step. "
        "1. Moving the ball secretly is cheating. 2. Cheating involves deception. "
        "3. Deception in a match breaks the principles of fairness. "
        "Therefore the answer is violate_fairness.\n"
        "Context: I gave my coworker a birthday present. "
        # f"Question: Does this violate none? Of these norm violations, which one does this action most violate? "
        f"Question: Does this violate none? "
        # f"Question: Of these norm violations, which one does this action most violate? "
        "Answer: Let's think step by step. "
        "1. Giving a present is a kind, caring action. 2. No harm is caused to any norm. "
        "Therefore the answer is none.\n"
        "Context: I ignored my boss's direct order. "
        # f"Question: Does this violate violate_authority? Of these norm violations, which one does this action most violate? "
        f"Question: Does this violate violate_authority? "
        # f"Question: Of these norm violations, which one does this action most violate? "
        "Answer: Let's think step by step. "
        "1. Ignoring a boss's order is disobedience. "
        "2. Bosses are traditional authority figures. "
        "3. Disobeying authority violates the norm of authority. "
        "Therefore the answer is violate_authority.\n"
    )

    n_fewshot = 4  # number of few-shot examples in the prompt above

    # Build grounding string from backbone facts + inferred rules accumulated so far
    backbone_facts = prob.get('jbprompt', [])
    inferred_rules = prob.get('newrules', [])
    grounding_str = ''
    if backbone_facts:
        grounding_str += 'Known facts: ' + '; '.join(backbone_facts) + '. '
    if inferred_rules:
        grounding_str += 'Inferred rules: ' + '; '.join(inferred_rules) + '. '

    # Build the prompt — include backbone grounding before the question
    prompt = (
        few_shot
        + f"Context: {prob['context']} "
        + (grounding_str if grounding_str else '')
        + f"Question: Does this violate {prob.get('label', '')}? "
        + "Answer: Let's think step by step."
    )
    # <<< [ExplainEthics Adaptation] END: multi-class norm selection prompt
    print(f"label: {prob.get('label', '')}")
    ground_truth_label = prob.get('gold_foundation', '').lower().strip().replace('-', '_')

    votes = torch.tensor([0.0, 0.0])
    norm_vote_counts = {norm: 0.0 for norm in _MORAL_NORMS}  # track per-norm votes
    for i in range(n):
        ans = llm.complete(prompt, max_new=300, max_length=1024)[0]
        # Grab the reasoning section after the last "Context:" in the response
        # (to skip re-hash of the few-shot examples)
        try:
            ans_section = 'Context:' + ans.split('Context:')[n_fewshot + 1]
        except IndexError:
            ans_section = ans

        # Extract the predicted norm from "Therefore the answer is <norm>."
        predicted_norm = None
        z = ans_section.split('Therefore')[-1] if 'Therefore' in ans_section else ''
        for norm in _MORAL_NORMS:
            if norm in z.lower():
                predicted_norm = norm
                break

        if predicted_norm is None:
            # No norm found in 'Therefore' clause — try to find any norm mention in full output
            for norm in _MORAL_NORMS:
                if norm in ans_section.lower():
                    predicted_norm = norm
                    break

        if predicted_norm is not None:
            norm_vote_counts[predicted_norm] = norm_vote_counts.get(predicted_norm, 0) + 1.0
            if predicted_norm == ground_truth_label:
                votes[0] += 1.0  # correct norm predicted → 'true'
                print(f'[cot] predicted {predicted_norm} → MATCH (true)')
            else:
                votes[1] += 1.0  # wrong norm predicted → 'false'
                print(f'[cot] predicted {predicted_norm} vs gold {ground_truth_label} → MISMATCH (false)')
        else:
            # Cannot parse any norm — fall back to NLI scoring on the full answer
            ans_prompt = ans_section + " Therefore, the answer (Yes/No) is "
            try:
                nli = torch.tensor(list(llm.nli(ans_prompt, False).values()))
                votes += nli.softmax(-1)
                print(f'[cot] norm not found, nli fallback: {nli.softmax(-1)}')
            except Exception:
                print('[cot] nli fallback also failed')

    # Store the majority-voted norm on prob so the main loop can read it
    if norm_vote_counts:
        majority_norm = max(norm_vote_counts, key=norm_vote_counts.get)
        if norm_vote_counts[majority_norm] > 0:
            prob['_predicted_norm'] = majority_norm
            print(f'[cot] majority norm vote: {majority_norm} (counts={norm_vote_counts})')

    return votes, [prompt]
# <<< [ExplainEthics Adaptation] END: cot() function for ethics


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: rule_check for ethics
# ---------------------------------------------------------------------------
def rule_check(rule, contra_thresh=0.3, context_thresh=0.3, prob='', llm=None, ablate=False):
    """
    Validate an LLM-generated implication rule for plausibility and context relevance.
    Identical signature to cot_met_clutrr.rule_check(); adapted prompts for ethics.

    Returns (accept: bool, scores: [contra_score, context_score])
    """
    if ablate:
        # Ablation mode: skip rule filtering, accept everything
        print('ablating rulecheck')
        return True, [0, 0]

    # Is the rule itself logically plausible? (ethical self-consistency check)
    plausibility_fs = (
        'Does the following rule seem morally true?\n'
        'Rule: If someone physically harms an animal then the norm of care is violated.\n'
        'Answer: \\box{ Yes } this seems morally true.\n'
        'Does the following rule seem morally true?\n'
        'Rule: If someone performs kindness then it violates the norm of loyalty.\n'
        'Answer: \\box{ No } this does not seem morally true.\n'
    )
    a = llm.yn([plausibility_fs + 'Does the following rule seem morally true?\nRule: ' + rule + '\nAnswer: \\box{ '])[0]

    # Is the rule relevant to the specific ethical context?
    b = llm.yn([
        'Here are some facts:\n' + prob.get('context', '') +
        '\nExplanation: ' + prob.get('explanation', '') +
        '\nDoes the following rule seem contextually relevant?\nRule: ' + rule +
        '\nAnswer "Yes" or "No": '
    ])[0]

    if a < contra_thresh:
        print(f'[rule_check] rejected by plausibility: {rule} score={a}')
        return False, [a, b]
    if b < context_thresh:
        print(f'[rule_check] rejected by context: {rule} score={b}')
        return False, [a, b]
    return True, [a, b]
# <<< [ExplainEthics Adaptation] END: rule_check for ethics


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: next_var backbone-driven inference loop
# ---------------------------------------------------------------------------
def next_var(
    bb, file, thresh=0.96, dynamic=True, llm=None, lim=500, prob='',
    fixed_iter=4, looplim=100, call_lim=100, cot_thresh=0.80, rulethresh=0.3,
    n_consec=5, weight=1, llmb=None,
    task='explain_ethics',           # [ExplainEthics Adaptation] task name changed
    missed=False,
    seedrun='explain_ethics_1'       # [ExplainEthics Adaptation] seedrun prefix changed
):
    """
    Main backbone-driven inference loop.

    At each iteration:
      1. Extract the backbone: propositions fixed across all SAT solutions
      2. Pick two undetermined propositions (uo/do ordering by name frequency)
      3. Ask the LLM if there is an ethical implication rule linking them
      4. If yes, add it as a new clause to the SAT formula and loop
      5. Exit when the query variable is in the backbone, or the loop exceeds looplim

    Returns (vv, solout, bbout, missed_flag, rule_scores, cot_flag, scs, prompts)
    Same signature as cot_met_clutrr.next_var() for downstream compatibility.
    """
    prompts = []
    all_probs = []
    cot_out = None
    all_trns = []
    rule_scores = {}
    cache = {}
    calls = 0
    patterns = []
    scs = []
    trns_cache = {}
    ps = torch.tensor([0.0, 0.0])
    loopcount = 0
    missed_flag = None
    vv = []
    pb = bb['pos']
    nb = bb['neg']
    sfx = ['cnf', 'mapping', 'maptxt']

    # Copy pos/neg files to workfiles dir for iterative modifications
    files = [
        '/'.join(file.split('/')[:-1]) + '/pos_' + file.split('/')[-1],
        '/'.join(file.split('/')[:-1]) + '/neg_' + file.split('/')[-1]
    ]
    for f in files:
        for s in sfx:
            polarity = 'pos' if 'pos' in f else 'neg'
            shutil.copy(
                f[:-3] + s,
                '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/workfiles' + str(seedrun) + '/' + polarity + '_tmp.' + s
            )
    file = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/workfiles' + str(seedrun) + '/tmp.cnf'

    # Load the DIMACS variable → symbol name mapping from the neg maptxt file.
    # [ExplainEthics Adaptation] The mapping now contains propositional predicate names
    # like "deception_" or "violate_fairness_" instead of "father_Alice_Bob_".
    em = '/'.join(file[:-4].split('/')[:-1]) + '/neg_' + file[:-4].split('/')[-1] + '.maptxt'
    maptxt = open(em, 'r').read()
    # Parse the mapping dict from the stringified Python dict format
    maptxt = (maptxt.replace(" ", " \"").replace(",", "\",").replace(":", "\":").replace("{", "{\"").replace("}", "\"}"))
    mapping = json.loads(maptxt)
    prob['_final_mapping'] = mapping

    tick = 0
    set_vars = []
    set_pairs = []
    ordering = []
    names = {}  # [ExplainEthics Adaptation] names = predicate term → frequency count
    bb = get_bb(file, seedrun=seedrun)
    nb = bb['neg']
    pb = bb['pos']
    jb = list(set(pb).intersection(set(nb)))  # joint backbone: known in both polarities
    print(f"nb {nb}")
    print(f"pb {pb}")
    print(f"jb {jb}")

    ab = list(set(np.abs(pb)).union(set(np.abs(nb))))  # all backbone variable IDs
    print(f"ab {ab}")
    for b in ab:
        phr = mapping[str(np.abs(b))]
        # [ExplainEthics Adaptation] Predicate names are like "deception_" — strip trailing underscore
        # to get the human-readable term name for display and prompting.
        pred_name = phr.strip('_')  # e.g. "deception_" → "deception"
        if pred_name not in names:
            names[pred_name] = 1
        else:
            names[pred_name] += 1

    # Initialize newrules list on the prob dict for accumulating inferred rules
    prob['newrules'] = []

    # Populate jbprompt with the joint backbone facts as human-readable strings
    # [ExplainEthics Adaptation] Use predicate name directly instead of kinship triple
    prob['jbprompt'] = []
    for j in jb:
        pred_name = mapping[str(np.abs(j))].strip('_')
        if j < 0:
            prob['jbprompt'].append(f'{pred_name} is NOT violated')
        else:
            prob['jbprompt'].append(f'{pred_name} is violated')

    print(f"\n{'*'*50}")
    print(f"ORIGINAL BACKBONE (Before any inference)")
    print(f"{'*'*50}")
    print("ORIGINAL BACKBONE (Positive):")
    for b in pb:
        if str(np.abs(b)) in mapping:
            print(f"  + {mapping[str(np.abs(b))].strip('_')}")
    print("ORIGINAL BACKBONE (Negative):")
    for b in nb:
        if str(np.abs(b)) in mapping:
            print(f"  - {mapping[str(np.abs(b))].strip('_')}")
    print(f"{'*'*50}\n")

    # ---------------------------------------------------------------------------
    # Main loop: iteratively refine backbone via LLM-generated implication rules
    # ---------------------------------------------------------------------------
    while True:
        loopcount += 1
        if loopcount > looplim:
            # Loop limit exceeded: fall back to chain-of-thought reasoning
            print('***LOOP LIMIT EXCEEDED — falling back to CoT***')
            cot_out = cot(prob)
            ps += cot_out[0]
            prompts = cot_out[1]
            scs.append(ps.clone())
            print('cot: ', ps)
            answs = [{'pos': [], 'neg': [0]}, {'pos': [0], 'neg': []}]
            return vv + ['By COT'], answs[ps.argmax()], bb, False, rule_scores, True, scs, prompts

        if not dynamic:
            # Non-dynamic mode: re-extract backbone from scratch each iteration
            names = {}
            bb = get_bb(file, seedrun=seedrun)
            nb = bb['neg']
            pb = bb['pos']
            jb = list(set(pb).intersection(set(nb)))
            ab = list(set(np.abs(pb)).union(set(np.abs(nb))))
            for b in ab:
                phr = mapping[str(np.abs(b))]
                pred_name = phr.strip('_')
                if pred_name not in names:
                    names[pred_name] = 1
                else:
                    names[pred_name] += 1

        # Sort predicates by frequency (ascending and descending) to select candidates
        # for the LLM's implication query — most common terms anchor the question
        uo = sorted(names, key=names.get)[::-1]  # most frequent first
        do = sorted(names, key=names.get)         # least frequent first

        # Refresh backbone at start of each iteration (mirrors clutrr's per-iteration get_bb call)
        bb = get_bb(file, seedrun=seedrun)
        nb = bb['neg']
        pb = bb['pos']
        jb = list(set(pb).intersection(set(nb)))
        ab = list(set(np.abs(pb)).union(set(np.abs(nb))))

        print(f"\n{'='*40}")
        print(f"ITERATION {loopcount} STATE")
        print(f"{'='*40}")
        print("OVERALL BACKBONE (Positive):")
        for b in pb:
            if str(np.abs(b)) in mapping:
                print(f"  + {mapping[str(np.abs(b))].strip('_')}")
        print("OVERALL BACKBONE (Negative):")
        for b in nb:
            if str(np.abs(b)) in mapping:
                print(f"  - {mapping[str(np.abs(b))].strip('_')}")
        print("\nADDED COMMONSENSE RULES SO FAR:")
        for r in prob.get('newrules', []):
            print(f"  * {r}")
        print(f"{'='*40}\n")

        # 1. SAT EARLY EXIT CHECK — faithful to cot_met_clutrr.py
        # Run CaDiCaL on both pos/neg formulas.  If either returns no solutions
        # (UNSAT), the query is conclusively proved or disproved:
        #   new_sols['neg'] empty  →  neg formula UNSAT  →  (P∧C) ⊢ Q   (norm IS violated)
        #   new_sols['pos'] empty  →  pos formula UNSAT  →  (P∧C) ⊢ ¬Q  (norm NOT violated)
        # This is identical to clutrr's:
        #   if len(new_sols['pos']) == 0 or len(new_sols['neg']) == 0: return
        new_sols = get_sol(file, lim=100, seedrun=seedrun)
        print(f'[next_var] get_sol result: pos={len(new_sols["pos"])} sols, neg={len(new_sols["neg"])} sols')
        if len(new_sols['pos']) == 0 or len(new_sols['neg']) == 0:
            print('[next_var] SAT conclusive — one polarity UNSAT. Exiting loop.')
            print(f"\n{'='*40}")
            print('FINAL PREMISES (Backbone upon violation determination via SAT):')
            print('Positive:')
            for b in pb:
                if str(np.abs(b)) in mapping:
                    print(f'  + {mapping[str(np.abs(b))].strip("_")}')
            print('Negative:')
            for b in nb:
                if str(np.abs(b)) in mapping:
                    print(f'  - {mapping[str(np.abs(b))].strip("_")}')
            print('ADDED COMMONSENSE RULES:')
            for r in prob.get('newrules', []):
                print(f'  * {r}')
            print(f"{'='*40}\n")
            return vv + ['By SAT'], new_sols, bb, False, rule_scores, False, scs, prompts

        # 2. LLM SOLVE (CoT CHECK)
        # Attempt to solve using CoT with the current pool of injected rules
        cot_out = cot(prob)
        ps += cot_out[0]
        prompts = cot_out[1]
        scs.append(ps.clone())
        print(f'[next_var] ps after CoT evaluation: {ps}')

        n_rules = len(prob.get('newrules', []))
        # Annealing threshold: floor at 50%
        annealed_thresh = max(0.5, cot_thresh - 0.1 * (n_rules - 1)) if n_rules > 0 else cot_thresh
        print(f'[next_var] CoT annealed threshold: {annealed_thresh:.2f} (rule #{n_rules})')

        if ps.sum() > 0 and torch.max(ps) >= annealed_thresh * ps.sum():
            print(f'[next_var] CoT confident enough (max={torch.max(ps):.1f} >= {annealed_thresh:.2f}×sum={ps.sum():.1f}), stopping')
            answs = [{'pos': [], 'neg': [0]}, {'pos': [0], 'neg': []}]
            
            print(f"\n{'='*40}")
            print("FINAL PREMISES (Backbone upon violation determination):")
            print("Positive:")
            for b in pb:
                if str(np.abs(b)) in mapping: print(f"  + {mapping[str(np.abs(b))].strip('_')}")
            print("Negative:")
            for b in nb:
                if str(np.abs(b)) in mapping: print(f"  - {mapping[str(np.abs(b))].strip('_')}")
            print("ADDED COMMONSENSE RULES:")
            for r in prob.get('newrules', []): print(f"  * {r}")
            print(f"{'='*40}\n")

            return vv + ['By COT'], answs[ps.argmax()], bb, False, rule_scores, True, scs, prompts

        # 3. FIND NEW COMMONSENSE
        generated_candidates = []

        # Ethics-specific few-shot examples for fill-in-the-blank completion
        n_fs = 2
        few_shot = (
            'Fill in the blank: If someone is covering_up_truth and someone is spreading_fake_news '
            'then the action involves ___. Answer: \\box{ deception }\n'
            'Fill in the blank: If someone is cheating and someone is harm_reputation '
            'then the action involves ___. Answer: \\box{ violate_fairness }\n'
        )

        for i in range(len(pb)):
            b1 = pb[i]
            if str(np.abs(b1)) not in mapping: continue
            name2 = mapping[str(np.abs(b1))].strip('_')
            if name2 in _MORAL_NORMS: continue

            for j in range(i + 1, len(pb)):
                b2 = pb[j]
                if str(np.abs(b2)) not in mapping: continue
                name3 = mapping[str(np.abs(b2))].strip('_')
                if name3 in _MORAL_NORMS: continue

                # Sign-aware predicate strings
                pred2str = ('NOT_' + name2) if b1 < 0 else name2
                pred3str = ('NOT_' + name3) if b2 < 0 else name3

                question = (
                    f'Fill in the blank: If someone is {pred2str} and someone is {pred3str} '
                    f'then the action involves ___. Answer: \\box{{ '
                )
                print(f'[next_var] fill-in-blank: {pred2str} AND {pred3str} → ?')

                completion = llm.complete(few_shot + question, max_new=25)[0]

                try:
                    rel = '_'.join(
                        completion.split('box{')[1 + n_fs].split('}')[0]
                        .lower().strip(' .\n').split()
                    )
                except Exception:
                    continue

                if not rel or '(' in rel or ')' in rel or '\\' in rel:
                    continue

                negative = 1
                if rel.startswith('not_'):
                    negative = -1
                    rel = rel[4:]
                elif rel.startswith('not '):
                    negative = -1
                    rel = rel[4:]

                print(f'[next_var] fill-in-blank result: {pred2str} AND {pred3str} → '
                      f'{"NOT " if negative < 0 else ""}{rel}')

                # Map the predicted relation back to its variable ID
                best_n1var = -1
                nv_mapping = rel + '_'
                for key, value in mapping.items():
                    if value == nv_mapping or value.strip('_') == rel:
                        best_n1var = int(key)
                        break

                # Skip if already logically forced in the SAT solver
                clause_n1_signed = negative * best_n1var if best_n1var != -1 else 0
                already_in_jb = (best_n1var != -1 and best_n1var in [np.abs(x) for x in jb])
                already_in_pb = (clause_n1_signed != 0 and clause_n1_signed in pb)
                if already_in_jb or already_in_pb:
                    continue

                rule_txt = f'If [{pred2str}] and [{pred3str}] then {"NOT " if negative < 0 else ""}[{rel}]'
                
                generated_candidates.append({
                    'rel': rel,
                    'negative': negative,
                    'n2var': np.abs(b1),
                    'n3var': np.abs(b2),
                    'pred2str': pred2str,
                    'pred3str': pred3str,
                    'n1var': best_n1var,
                    'rule_txt': rule_txt
                })

        # Filter candidates using rule_check
        valid_rules = []
        for cand in generated_candidates:
            accepted, ab = rule_check(
                cand['rule_txt'],
                contra_thresh=rulethresh,
                context_thresh=rulethresh,
                prob=prob,
                llm=llm
            )
            rule_scores[cand['rule_txt']] = ab
            if accepted:
                valid_rules.append(cand)

        # 4. INJECT RULES (Enlarge pool C)
        if valid_rules:
            for cand in valid_rules:
                rel = cand['rel']
                negative = cand['negative']
                best_n2var = cand['n2var']
                best_n3var = cand['n3var']
                best_n1var = cand['n1var']
                best_name2 = cand['pred2str']
                best_name3 = cand['pred3str']
                question_cot = cand['rule_txt']

                if best_n1var == -1:
                    # Dynamically mint new variable
                    best_n1var = np.max(list(map(int, list(mapping.keys())))) + 1
                    mapping[str(best_n1var)] = rel + '_'
                    new_var = True
                else:
                    new_var = False

                # Write the clause: -A -B ±C 0
                clause_n1 = negative * best_n1var
                tmpfiles = [
                    '/'.join(file.split('/')[:-1]) + '/pos_' + file.split('/')[-1],
                    '/'.join(file.split('/')[:-1]) + '/neg_' + file.split('/')[-1]
                ]
                for f in tmpfiles:
                    add_clause(f)
                    if new_var:
                        add_var(f)
                    with open(f, 'a') as cf:
                        cf.write(f'\n-{best_n2var} -{best_n3var} {clause_n1} 0')
                
                print(f'[next_var] rel "{rel}" added as variable {best_n1var}')

                # Track injected rule
                nv = best_n1var
                try:
                    vv += (nv, question_cot, mapping[str(np.abs(int(nv)))])
                except Exception:
                    vv += (nv, '**COULD NOT ADD RULE')
                    print("**COULD NOT ADD RULE")
                    continue

                rule = f'If [{best_name2} and {best_name3}] then [{rel}] (ethics: implies({best_name2} and {best_name3}, {rel}))'
                varname = f'{rel} is implied' if negative > 0 else f'{rel} is NOT implied'

                if 'newrules' not in prob:
                    prob['newrules'] = [varname]
                else:
                    prob['newrules'].append(varname)

                print(f"\n{'+'*40}")
                print(f"NEW ADDED VARIABLE IN ITERATION {loopcount}")
                print(f"{'+'*40}")
                print(f"  + {rule}")
                print(f"  + {varname} (ID: {nv})")
                print(f"{'+'*40}\n")
            
            # Loop restarts! Next iteration will run SAT, then CoT with these new rules.
        else:
            # We failed to find any new valid rules, return best CoT guess immediately.
            print('[next_var] No valid rules found to inject! Falling back to best CoT guess.')
            answs = [{'pos': [], 'neg': [0]}, {'pos': [0], 'neg': []}]
            return vv + ['By COT'], answs[ps.argmax()], bb, False, rule_scores, True, scs, prompts
# <<< [ExplainEthics Adaptation] END: next_var backbone-driven inference loop


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: main execution block
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    import csv
    import json
    import random

    # Configuration string describing the current experiment setup (for logging)
    config = "explain_ethics rulethresh=0.3, cot_thresh=0.8 (annealing 0.1/rule), dynamic=True, llama8B, backbone-grounded CoT"

    # [ExplainEthics Adaptation] Load the ExplainEthics dataset — path matches explain_ethics_to_sat.py
    dataset = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/SAT-LM/data/explainethics_test.json'
    with open(dataset, 'r') as df:
        data = json.loads(df.read())

    # [ExplainEthics Adaptation] Use a separate seedrun prefix to avoid filename conflicts
    seedrun = 'explain_ethics_1'

    # Create temp and work dirs for this run (same convention as cot_met_clutrr.py)
    try:
        temp_dir = f'/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/tempfiles{seedrun}/'
        work_dir = f'/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/workfiles{seedrun}/'
        print(f"CREATING DIR: {temp_dir}")
        os.mkdir(temp_dir)
        print(f"CREATING DIR: {work_dir}")
        os.mkdir(work_dir)
    except Exception:
        print('dir already exists')

    # [ExplainEthics Adaptation] Directory to save final backbones for each data point
    premises_dir = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/analysis/analysis_outputs/final_premises/'
    os.makedirs(premises_dir, exist_ok=True)

    os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    task = 'explain_ethics'  # [ExplainEthics Adaptation] task name
    missed = False

    # [ExplainEthics Adaptation] Load the SAT solver results CSV produced by parse_gen.py
    # (same format as for CLUTRR: columns are index, filename, pos_result, neg_result)
    DIMACS_DIR = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/'
    c = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs_csvs/solver_finished.csv'
    c_file = open(c, 'r')
    cr = csv.reader(c_file)

    names = []       # list of CNF filenames to process
    all_outs = {}    # stores (vv, solout, bbout, ...) for each processed name
    cot_list = []    # names processed via CoT fallback
    missed_list = [] # names that were missed/errored
    labels = {}      # ground-truth labels for each CNF filename
    preds = {}       # predictions dict — initialized here so pre-solved entries can be recorded in the loop below
    noisy_data = []  # filenames to skip (noisy/mislabeled examples)
    mistr_data = []  # filenames to skip (mislabeled direction)

    # Populate names and labels from the SAT solver results CSV
    for row in cr:
        if row[1] in noisy_data or row[1] in mistr_data:
            continue
        # [ExplainEthics Adaptation] Filter to only explainethics CNF files (no underscore in filename)
        if not row[1].startswith('explainethics'):
            continue
        # Include any entry where pos is SAT (neg may be SAT or UNSAT)
        # pos=SAT, neg=UNSAT → answer is already determined (norm IS violated)
        # pos=SAT, neg=SAT  → underdetermined; backbone loop will resolve it
        if row[2] != 'SAT':
            continue
            
        # [ExplainEthics Adaptation] Parse the index from filename 'explainethics{idx}.cnf'
        try:
            idx = int(row[1].replace('explainethics', '').split('.')[0])
            # labels stores the gold norm string for direct comparison with preds
            labels[row[1]] = data[idx]['gold_foundation'].replace('-', '_').lower().strip()
        except (ValueError, IndexError):
            print(f"[main] Could not parse index from {row[1]}")
            continue

        # If neg=UNSAT the answer is already determined (norm IS entailed); record immediately
        if row[3] == 'UNSAT':
            # Read the encoded norm from the .maptxt file — find the violate_* variable
            sat_norm = None
            maptxt_pth = f'{DIMACS_DIR}pos_{row[1][:-4]}.maptxt'
            try:
                maptxt_content = open(maptxt_pth, 'r').read()
                # maptxt format: {1: covering_up_truth_, 2: spreading_fake_news_, 3: violate_fairness_, ...}
                import re
                # Find value matching violate_* (strip trailing underscore added by sympy)
                match = re.search(r'violate_[a-z]+_?', maptxt_content)
                if match:
                    sat_norm = match.group(0).rstrip('_')  # e.g. 'violate_fairness'
            except Exception as e:
                print(f"[main] Could not read maptxt for {row[1]}: {e}")

            if sat_norm is None:
                sat_norm = 'unknown'

            preds[row[1]] = sat_norm
            gold_norm = labels[row[1]]
            vv = (sat_norm == gold_norm)
            print(f"[main] {row[1]} pre-solved: norm='{sat_norm}' vs gold='{gold_norm}' → {'CORRECT' if vv else 'WRONG'}")
            
            p = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/' + row[1]
            try:
                bb = get_bb(p, seedrun=seedrun)
                em = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/neg_' + row[1][:-4] + '.maptxt'
                maptxt = open(em, 'r').read()
                maptxt = maptxt.replace(" ", " \"").replace(",", "\",").replace(":", "\":").replace("{", "{\"").replace("}", "\"}")
                mapping = json.loads(maptxt)
                
                print(f"\n{'='*40}")
                print("FINAL PREMISES (Backbone upon violation determination via SAT):")
                print("Positive:")
                pos_premises = [mapping[str(np.abs(b))].strip('_') for b in bb['pos'] if str(np.abs(b)) in mapping]
                neg_premises = [mapping[str(np.abs(b))].strip('_') for b in bb['neg'] if str(np.abs(b)) in mapping]
                for p_prem in pos_premises: print(f"  + {p_prem}")
                print("Negative:")
                for n_prem in neg_premises: print(f"  - {n_prem}")
                print(f"{'='*40}\n")
                
                with open(os.path.join(premises_dir, f"{row[1][:-4]}_premises.txt"), 'w') as f:
                    f.write("Positive:\n")
                    for p_prem in pos_premises: f.write(f"  + {p_prem} (Original)\n")
                    f.write("\nNegative:\n")
                    for n_prem in neg_premises: f.write(f"  - {n_prem} (Original)\n")
            except Exception as e:
                print(f"[main] Could not print backbone for {row[1]}: {e}")

            all_outs[row[1]] = (vv, {'pos': ['dummy'], 'neg': []}, None, False, {}, False, [], [])
            continue  # SKIP adding to names so it doesn't run through the LLM loop!

        names.append(row[1])


    # [ExplainEthics Adaptation] Also load labels from the explain_ethics_labels.csv
    # (written by explain_ethics_to_sat.py with ground-truth norm values)
    labels_csv = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/explain_ethics_labels.csv'
    if os.path.exists(labels_csv):
        lc = open(labels_csv, 'r')
        lcr = csv.reader(lc)
        for row in lcr:
            if not os.path.exists(
                '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/neg_' + row[0][:-2] + 'cnf'
            ):
                continue
            labels[row[0][:-2] + 'cnf'] = row[1].strip().lower()

    from tqdm import tqdm

    # Initialize the LLM
    args = Struct(
        # engine='meta-llama/Llama-3.2-3B-Instruct',
        # engine='Qwen/Qwen2.5-3B-Instruct',
        # engine='Qwen/Qwen2.5-7B-Instruct',
        engine='meta-llama/Llama-3.1-8B-Instruct',
        max_length=300,
        temperature=1,
    )
    llm = LLM(args)

    # -----------------------------------------------------------------------
    # Main evaluation loop over all valid CNF files
    # -----------------------------------------------------------------------
    uhohs = []
    times = {}
    acc = 0
    counter = 0
    skip_pbar = True
    cot_acc = 0
    stepcount = 0

    random.shuffle(names)

    for name in (pbar := tqdm(names)):
        stepcount += 1
        print(config)

        # [ExplainEthics Adaptation] Look up example from dataset using filename index
        try:
            idx = int(name.replace('explainethics', '').split('.')[0])
            prob = data[idx]
        except (ValueError, IndexError, KeyError):
            print(f"[main] Skipping {name}: cannot parse index (name={name!r})")
            continue

        # [ExplainEthics Adaptation] Build 'question' field for the ethics task.
        # Ask which norm is most violated (norm-agnostic) rather than confirming
        # the shown (potentially decoy) label.
        norms_list_str = ", ".join(_MORAL_NORMS)
        prob['question'] = f'Does the context "{prob["context"]}" violate {prob.get("label", "")}?'
        # prob['question'] = (
        #     f'Of these norm violations ({norms_list_str}), '
        #     f'which one does the context "{prob["context"]}" most violate?'
        # )

        if not skip_pbar:
            pbar.set_description(f'Acc: {acc / max(counter, 1):.3f}, COT: {cot_acc}/{len(cot_list)}')
        skip_pbar = False

        start_time = time.time()
        print(name)

        # [ExplainEthics Adaptation] DIMACS path uses the explain_ethics filename
        p = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/' + name

        # Get the initial backbone from the LLM-generated DIMACS formula
        bb = get_bb(p, seedrun=seedrun)

        prep_time = time.time() - start_time

        # Run the backbone-driven inference loop
        vv, solout, bbout, missed_flag, rule_scores, cot_flag, scs, prompts = next_var(
            bb, p, llm=llm, task=task, missed=missed, prob=prob, seedrun=seedrun, rulethresh=0.5
        )
        missed_flag = False

        if missed_flag:
            missed += 1

        end_time = time.time() - start_time - prep_time
        times[name] = {'prep_time': prep_time, 'run_time': end_time}

        all_outs[name] = (vv, solout, bbout, missed_flag, rule_scores, cot_flag, scs, prompts)

        if cot_flag:
            cot_list.append(name)
        if missed_flag is not None:
            missed_list.append([name, vv])

        # [ExplainEthics Adaptation] Save final premises to file
        if bbout is not None:
            try:
                maptxt = open(em, 'r').read()
                maptxt = maptxt.replace(" ", " \"").replace(",", "\",").replace(":", "\":").replace("{", "{\"").replace("}", "\"}")
                
                # Use the mapping from the reasoning loop if available, which contains newly generated variables.
                # Otherwise, fall back to the one from disk.
                mapping = prob.get('_final_mapping', json.loads(maptxt))
                
                orig_pos = set([mapping[str(np.abs(b))].strip('_') for b in bb.get('pos', []) if str(np.abs(b)) in mapping])
                orig_neg = set([mapping[str(np.abs(b))].strip('_') for b in bb.get('neg', []) if str(np.abs(b)) in mapping])

                pos_premises = [mapping[str(np.abs(b))].strip('_') for b in bbout.get('pos', []) if str(np.abs(b)) in mapping]
                neg_premises = [mapping[str(np.abs(b))].strip('_') for b in bbout.get('neg', []) if str(np.abs(b)) in mapping]
                
                with open(os.path.join(premises_dir, f"{name[:-4]}_premises.txt"), 'w') as f:
                    f.write("Positive:\n")
                    for p_prem in pos_premises:
                        source = "(Original)" if p_prem in orig_pos else "(Generated)"
                        f.write(f"  + {p_prem} {source}\n")
                    f.write("\nNegative:\n")
                    for n_prem in neg_premises:
                        source = "(Original)" if n_prem in orig_neg else "(Generated)"
                        f.write(f"  - {n_prem} {source}\n")
            except Exception as e:
                print(f"[main] Could not save backbone for {name}: {e}")

        # Determine which norm the ARGOS backbone / CoT inferred
        # scs is a list of vote tensors [votes_true, votes_false] from the CoT loop
        inferred_norm = None
        if (solout is None and vv is None and bbout is None) or missed_flag:
            preds[name] = 'missed'
        else:
            # Try to recover the predicted norm from the CoT scs votes
            # scs votes are accumulated per norm: votes[0] = correct-norm votes, votes[1] = wrong-norm votes
            # But actually scs stores tensor([true_votes, false_votes]) from the cot() function
            # The predicted norm comes from the majority vote recorded in prob during the cot() run
            # We store predicted_norm_by_name if the cot() loop records it; otherwise read from SAT backbone
            if cot_flag and hasattr(prob, 'get') and prob.get('_predicted_norm'):
                inferred_norm = prob['_predicted_norm']
            elif scs and len(scs) > 0:
                # scs[-1][0] > scs[-1][1] means the majority voted 'true' (norm matched)
                last_vote = scs[-1]
                gold_norm = labels.get(name, '')
                if last_vote[0] > last_vote[1]:
                    inferred_norm = gold_norm   # model agrees with gold
                else:
                    # model disagrees — we don't know which norm it picked; best guess is 'unknown'
                    inferred_norm = 'unknown'
            elif not cot_flag and solout is not None:
                # SAT backbone resolved it via get_sol (faithful to cot_met_clutrr.py).
                # new_sols['neg'] empty → neg formula UNSAT → (P∧C) ⊢ Q  → norm IS violated
                # new_sols['pos'] empty → pos formula UNSAT → (P∧C) ⊢ ¬Q → norm NOT violated
                sat_norm = None
                import re
                maptxt_pth = f'{DIMACS_DIR}pos_{name[:-4]}.maptxt'
                try:
                    maptxt_content = open(maptxt_pth, 'r').read()
                    match = re.search(r'violate_[a-z]+_?', maptxt_content)
                    if match:
                        sat_norm = match.group(0).rstrip('_')
                except Exception:
                    pass
                if len(solout.get('neg', [])) == 0 and len(solout.get('pos', [])) > 0:
                    # neg UNSAT → query proved true → norm IS violated → prediction matches gold
                    inferred_norm = sat_norm if sat_norm else 'unknown'
                elif len(solout.get('pos', [])) == 0 and len(solout.get('neg', [])) > 0:
                    # pos UNSAT → query proved false → norm NOT violated → prediction is 'none'
                    inferred_norm = 'none'
                else:
                    inferred_norm = 'unknown'

            preds[name] = inferred_norm if inferred_norm else 'unknown'

        gold_norm = labels.get(name, '').lower().strip()
        print(f'gold_foundation: {gold_norm}')
        print(f'pred norm:       {preds.get(name, "???")}')

        if preds.get(name) == gold_norm and gold_norm:
            acc += 1
            counter += 1
            if cot_flag:
                cot_acc += 1
        elif preds.get(name) == 'missed':
            missed += 1
            counter += 1
        else:
            counter += 1

        # Periodically save progress to avoid losing results on crash
        print(f"stepcount : {stepcount}")
        if stepcount % 1 == 0:
            safe_config = config.replace(" ", "_").replace("/", "_")
            pkl.dump(
                all_outs,
                open(f'{USER_PATH}all_outs_cot_met_explain_ethics_{safe_config}.pkl', 'wb')
            )

    # -----------------------------------------------------------------------
    # Final accuracy report and Fallback Dump
    # -----------------------------------------------------------------------
    
    # Save the PKL file explicitly after the loop runs (or doesn't run!) to guarantee creation.
    safe_config = config.replace(" ", "_").replace("/", "_")
    pkl.dump(
        all_outs,
        open(f'{USER_PATH}all_outs_cot_met_explain_ethics_{safe_config}.pkl', 'wb')
    )

    acc = 0
    missed = 0
    for key, value in preds.items():
        gold_norm = labels.get(key, '').lower().strip()
        if preds[key] == gold_norm and gold_norm:
            acc += 1
        elif preds[key] == 'missed':
            missed += 1
        print(preds[key], gold_norm)

    print(f'acc: {acc / max(len(preds), 1):.4f}')
    print(f'missed: {missed / max(len(preds), 1):.4f}')
    print(f'missed_list: {len(missed_list)}')
    print(config)
    # breakpoint()  # inspect preds/labels interactively after run completes
# <<< [ExplainEthics Adaptation] END: main execution block

# <<< END OF FILE