"""
cot_met_explain_ethics.py
==========================
ExplainEthics adaptation of main/argos/cot_met_clutrr.py.

Purpose
-------
This is the main reasoning loop for running the ARGOS/SAT-LM pipeline on
the ExplainEthics dataset. It mirrors cot_met_clutrr.py structurally but
adapts every domain-specific part for moral reasoning:

  - Dataset: hard_question.json instead of clutrr_test.json
  - Variable names: propositional implies() predicates instead of kinship relations
  - Labels: moral norms (violate_care, etc.) instead of family relations
  - Question format: "Does [context] violate [norm]?" instead of "Is X Y's relation?"
  - Backbone variable extraction: predicate names instead of person name pairs

Pipeline flow (same as cot_met_clutrr.py):
  1. Load dimacs/ SAT files generated by explain_ethics_to_sat.py
  2. Get backbone (get_bb) → set of literals that hold across all SAT solutions
  3. Run next_var() loop:
     a. Extract unresolved backbone literals → moral predicate candidates
     b. Ask LLM to generate an implies() rule connecting the candidates
     c. Add the rule to the SAT formula and re-extract the backbone
     d. If the backbone becomes conclusive, report True/False
     e. If the loop limit is reached, fall back to Chain-of-Thought (cot())
  4. Compare prediction vs ground-truth labels; compute accuracy

# >>> [ExplainEthics Adaptation] BEGIN: Module
"""

import os
import shutil
import numpy as np
import time
import json
import random
from dotenv import load_dotenv

# Load .env for HF_TOKEN etc.
load_dotenv()

import torch
from torch.utils.data import DataLoader

# All paths are relative to the WSL mount of the Windows project directory
USER_PATH = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/'

os.environ["CURL_CA_BUNDLE"] = ""
os.environ["REQUESTS_CA_BUNDLE"] = ""
cache_dir = os.path.join(os.getcwd(), '.cache/huggingface/hub')
os.environ['TRANSFORMERS_CACHE'] = cache_dir
os.environ['HF_HOME'] = cache_dir

import pickle as pkl
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import argparse
from tqdm import tqdm
import time
import datetime
import warnings
import contextlib
import requests
from urllib3.exceptions import InsecureRequestWarning

# ---------------------------------------------------------------------------
# SSL verification bypass (same as cot_met_clutrr.py) to handle internal proxy
# ---------------------------------------------------------------------------
old_merge_environment_settings = requests.Session.merge_environment_settings

@contextlib.contextmanager
def no_ssl_verification():
    opened_adapters = set()

    def merge_environment_settings(self, url, proxies, stream, verify, cert):
        opened_adapters.add(self.get_adapter(url))
        settings = old_merge_environment_settings(self, url, proxies, stream, verify, cert)
        settings['verify'] = False
        return settings

    requests.Session.merge_environment_settings = merge_environment_settings
    try:
        with warnings.catch_warnings():
            warnings.simplefilter('ignore', InsecureRequestWarning)
            yield
    finally:
        requests.Session.merge_environment_settings = old_merge_environment_settings
        for adapter in opened_adapters:
            try:
                adapter.close()
            except:
                pass


class Struct:
    """Simple namespace class to convert dicts to attribute-accessible objects."""
    def __init__(self, **entries):
        self.__dict__.update(entries)


# ---------------------------------------------------------------------------
# LLM wrapper — identical to cot_met_clutrr.py; kept self-contained here
# so this file can be run without importing cot_met_clutrr.py
# ---------------------------------------------------------------------------
class LLM():
    """
    Thin wrapper around a HuggingFace causal LM.
    Provides sentence probability scoring (for NLI-style yes/no), completion,
    and yes/no prediction helpers (yn).
    """
    def __init__(self, args):
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype="bfloat16",
            bnb_4bit_use_double_quant=True,
        )
        with no_ssl_verification():
            self.tokenizer = AutoTokenizer.from_pretrained(
                args.engine,
                cache_dir=cache_dir,
                token=os.getenv("HF_TOKEN"),
                trust_remote_code=False
            )
            self.tokenizer.pad_token = self.tokenizer.eos_token
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
            self.tokenizer.padding_side = "left"

            self.model = AutoModelForCausalLM.from_pretrained(
                args.engine,
                cache_dir=cache_dir,
                quantization_config=quant_config,
                device_map='auto',
                token=os.getenv("HF_TOKEN"),
                attn_implementation="sdpa",
                trust_remote_code=False
            )
            self.model.config.use_cache = True

    @property
    def device(self):
        return next(self.model.parameters()).device

    _kv_cache_reported = False

    def sentence_probabilities(self, sentences):
        """Return log-probabilities for each sentence (used for NLI scoring)."""
        with torch.no_grad():
            sentence_tokens = self.tokenizer(sentences, return_tensors='pt', padding=True)
            sentence_token_ids = sentence_tokens.input_ids.to(self.device)
            attention_mask = sentence_tokens.attention_mask.to(self.device)

            first_different_token = (
                sentence_token_ids == sentence_token_ids[0, :].unsqueeze(0)
            ).all(dim=0).long().argmin()
            common_prefix = sentence_token_ids[0, :first_different_token].unsqueeze(0)
            common_prefix_output = self.model(common_prefix, use_cache=True)
            pkv = common_prefix_output.past_key_values

            expanded_pkv = None
            try:
                from transformers.cache_utils import DynamicCache
                import transformers
                transformers_version = tuple(int(x) for x in transformers.__version__.split(".")[:2])

                if isinstance(pkv, DynamicCache):
                    if transformers_version >= (4, 43):
                        # New API: key_cache / value_cache lists
                        if pkv.key_cache and all(k is not None and v is not None
                                for k, v in zip(pkv.key_cache, pkv.value_cache)):
                            new_cache = DynamicCache()
                            for k, v in zip(pkv.key_cache, pkv.value_cache):
                                new_cache.key_cache.append(k.expand(len(sentences), -1, -1, -1).contiguous())
                                new_cache.value_cache.append(v.expand(len(sentences), -1, -1, -1).contiguous())
                            expanded_pkv = new_cache
                    else:
                        # Old API: iterate over layers directly as (key, value) tuples
                        layers = list(pkv)
                        if layers and all(t is not None for layer in layers for t in layer):
                            expanded_pkv = tuple(
                                tuple(t.expand(len(sentences), -1, -1, -1).contiguous() for t in layer)
                                for layer in layers
                            )
                elif pkv is not None:
                    # Legacy pure tuple-of-tuples format
                    if all(t is not None for layer in pkv for t in layer):
                        expanded_pkv = tuple(
                            tuple(t.expand(len(sentences), -1, -1, -1).contiguous() for t in layer)
                            for layer in pkv
                        )
            except Exception as e:
                print(f'KV-cache expansion failed: {e}')
                expanded_pkv = None

            if expanded_pkv is not None:
                if not LLM._kv_cache_reported:
                    print(f"[KV-cache] ACTIVE — {type(pkv).__name__}")
                    LLM._kv_cache_reported = True
                rest_outputs = self.model(
                    sentence_token_ids[:, first_different_token:],
                    past_key_values=expanded_pkv
                )
                logits = torch.concat(
                    [common_prefix_output.logits.expand(len(sentences), -1, -1), rest_outputs.logits],
                    dim=1
                ).to(self.device)
            else:
                if not LLM._kv_cache_reported:
                    print(f"[KV-cache] DISABLED — slow path")
                    LLM._kv_cache_reported = True
                full_outputs = self.model(sentence_token_ids, attention_mask=attention_mask)
                logits = full_outputs.logits.to(self.device)

            log_probs = logits.log_softmax(-1)
            log_probs = log_probs[:, :-1, :].gather(
                2, sentence_token_ids[:, 1:][:, :, None]
            ).squeeze(-1).to(self.device)
            log_probs = (log_probs * attention_mask[:, 1:]).sum(-1).cpu()
        return log_probs

    def nli(self, sentences, unknown):
        """Score True/False (or True/Unknown/False) probabilities for a sentence."""
        if unknown:
            true_probs, maybe_probs, false_probs = self.sentence_probabilities(
                [sentences + "(A)", sentences + "(B)", sentences + "(C)"]
            )
            return {'True': true_probs, 'Maybe': maybe_probs, 'False': false_probs}
        else:
            true_probs, false_probs = self.sentence_probabilities(
                [sentences + "(A)", sentences + "(B)"]
            )
            return {'True': true_probs, 'False': false_probs}

    def yn(self, sentences, norm=True, relaxed=False, obvious=False, unknown=False, fewshot=None, maybe=False):
        """
        Batch yes/no (or yes/maybe/no) predictions via log-probability scoring.
        Returns a list of probability tensors.
        """
        yns = []
        for sentence in sentences:
            if fewshot:
                sentence = fewshot + sentence
            if maybe:
                yns += [sentence + "Yes", sentence + "Maybe", sentence + "No"]
            elif unknown:
                yns += [sentence + "True", sentence + "Unknown", sentence + "False"]
            else:
                yns += [sentence + "Yes", sentence + "No"]
        probs = []
        batch_size = 256
        for i in range(0, len(yns), batch_size):
            probs += list(self.sentence_probabilities(yns[i:i + batch_size]))
        probs = torch.tensor(probs)
        pyes, pno, pmaybe = [], [], []
        z = 3 if (maybe or unknown) else 2
        for i in range(0, len(probs), z):
            if maybe or unknown:
                yes, mb, no = probs[i], probs[i + 1], probs[i + 2]
            else:
                yes, no = probs[i], probs[i + 1]
            if norm:
                if maybe or unknown:
                    y, m, n = torch.tensor([yes, mb, no]).softmax(-1)
                else:
                    y, n = torch.tensor([yes, no]).softmax(-1)
                pyes.append(y)
                pno.append(n)
                if maybe or unknown:
                    pmaybe.append(m)
            else:
                pyes.append(1 - yes / (yes + no))
        if maybe:
            return torch.stack([torch.tensor(pyes), torch.tensor(pmaybe), torch.tensor(pno)])
        if unknown:
            return [torch.tensor(pyes), torch.tensor(pmaybe), torch.tensor(pno)]
        return [torch.tensor(pyes), torch.tensor(pno)]

    def complete(self, prompt, max_new=25, temp=1, topk=0, max_length=300):
        """Generate a continuation for a given prompt string."""
        encoded = self.tokenizer(
            prompt,
            return_tensors='pt',
            padding=True,
            truncation=True,
            max_length=max_length
        )
        encode_ids = encoded.input_ids.to(self.device)
        attn_mask = encoded.attention_mask.to(self.device)
        generated_outputs = self.model.generate(
            encode_ids,
            attention_mask=attn_mask,
            pad_token_id=self.tokenizer.eos_token_id,
            max_new_tokens=max_new,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=(temp > 0 and topk > 0),
            temperature=temp if (temp > 0 and topk > 0) else None,
            top_k=topk if topk > 0 else None,
        )
        responses = self.tokenizer.batch_decode(
            generated_outputs.sequences,
            skip_special_tokens=True
        )
        return responses


# ---------------------------------------------------------------------------
# SAT formula helpers — identical to cot_met_clutrr.py; no domain changes needed
# >>> [ExplainEthics Adaptation] BEGIN: add_clause / add_var
# ---------------------------------------------------------------------------
def add_clause(file):
    """
    Increment the clause count in the DIMACS header by 1.
    Called before appending a new blocking clause to a .cnf file.
    """
    f = open(file, 'r')
    lines = f.readlines()
    writestr = ''
    for line in lines:
        if line.startswith('p cnf'):
            num_var, num_clause = line.split(' ')[2], line.split(' ')[3]
            writestr += 'p cnf ' + str(num_var) + ' ' + str(int(num_clause) + 1) + '\n'
        else:
            writestr += line
    f.close()
    f = open(file, 'w')
    f.write(writestr)
    f.close()


def add_var(file):
    """Increment the variable count in the DIMACS header by 1."""
    f = open(file, 'r')
    lines = f.readlines()
    writestr = ''
    for line in lines:
        if line.startswith('p cnf'):
            num_var, num_clause = line.split(' ')[2], line.split(' ')[3]
            writestr += 'p cnf ' + str(int(num_var) + 1) + ' ' + str(int(num_clause)) + '\n'
        else:
            writestr += line
    f.close()
    f = open(file, 'w')
    f.write(writestr)
    f.close()
# <<< [ExplainEthics Adaptation] END: add_clause / add_var


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: get_bb (backbone extraction)
# Backbone extraction — calls the CadiBack binary to find literals common to
# all SAT solutions. Identical mechanics to cot_met_clutrr.py.
# ---------------------------------------------------------------------------
def get_bb(file, del_sols=None, seedrun=0):
    """
    Run CadiBack on pos and neg polarity CNF files and return the backbone.
    The backbone is the set of literals that have the same truth value in ALL
    satisfying assignments — i.e. the things that MUST be true/false.

    Returns dict {'pos': [literals], 'neg': [literals]}.
    """
    bb = {'pos': [], 'neg': []}
    files = [
        '/'.join(file.split('/')[:-1]) + '/pos_' + file.split('/')[-1],
        '/'.join(file.split('/')[:-1]) + '/neg_' + file.split('/')[-1]
    ]
    for i in range(len(files)):
        cur_file = files[i]
        # Copy to tempfiles dir for isolated solver runs
        shutil.copy(
            cur_file,
            '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
        )

        if del_sols is not None:
            # Block previously seen solutions by adding their negations as clauses
            polarity = 'pos' if 'pos' in cur_file and 'neg' not in cur_file else 'neg'
            ds = del_sols[polarity]
            for sol in ds:
                add_clause(
                    '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1]
                )
                cf = open(
                    '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/' + cur_file.split('/')[-1], 'a'
                )
                write_str = '\n'
                for lit in sol:
                    write_str += str(-lit) + ' '
                cf.write(write_str)
                cf.close()

        # Run CadiBack to extract the backbone
        print('running cadiback for explain_ethics backbone extraction')
        bbone_pth = (
            '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/'
            + cur_file.split('/')[-1][:-4] + ".bbone"
        )
        print(f"[get_bb] Writing backbone to: {bbone_pth}")
        os.system(
            "timeout 5000 " + USER_PATH + "/main/cadiback/cadiback "
            + '/'.join(cur_file.split('/')[:-2]) + '/tempfiles' + str(seedrun) + '/'
            + cur_file.split('/')[-1] + '> ' + bbone_pth
        )

        try:
            bbone_f = open(bbone_pth, 'r')
            lines = bbone_f.readlines()
        except Exception as e:
            print(f"[get_bb] Failed to open bbone file: {e}")
            # breakpoint()
            continue
        for line in lines:
            if line.startswith('b'):
                # 'b' lines contain the backbone literals as space-separated integers
                lits = line.split(' ')[1:]
                for lit in lits:
                    lit = lit.strip()
                    if lit == '0':
                        continue
                    lit = int(lit)
                    if 'pos' in cur_file and 'neg' not in cur_file:
                        bb['pos'].append(lit)
                    elif 'neg' in cur_file:
                        bb['neg'].append(lit)

    return bb
# <<< [ExplainEthics Adaptation] END: get_bb


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: cot() function for ethics
# Chain-of-Thought fallback reasoning for moral norm classification.
# Unlike CLUTRR (which asks "Is X Y's relation?"), we ask "Does this scenario
# violate [norm]?" using ethical few-shot examples.
# ---------------------------------------------------------------------------
def cot(prob, n=5):
    """
    Run Chain-of-Thought moral reasoning as a fallback when the backbone loop
    cannot converge within the loop limit.

    Uses a few-shot prompt with ethical examples, then asks the LLM whether the
    given context violates the specified moral norm.

    Returns (votes: Tensor[2], prompts: list[str])
      votes[0] > votes[1]  → prediction is 'true'  (norm is violated)
      votes[1] > votes[0]  → prediction is 'false' (norm is not violated)
    """
    # Few-shot examples covering diverse moral norm violations for ethical reasoning.
    # These mirror the format used in cot_met_clutrr.py but for ethics.
    few_shot = (
        "Context: I crush the frog. "
        "Question: Does this violate care? "
        "Answer: Let's think step by step. "
        "1. Frogs are animals. 2. Crushing causes physical harm to an animal. "
        "3. The norm of care is violated if there is physical harm to an animal. "
        "Therefore the answer is Yes.\n"
        "Context: I won my match by moving my ball when the other player wasn't looking. "
        "Question: Does this violate fairness? "
        "Answer: Let's think step by step. "
        "1. Moving the ball secretly is cheating. 2. Cheating involves deception. "
        "3. Deception in a match breaks the principles of fairness. "
        "Therefore the answer is Yes.\n"
        "Context: I gave my coworker a birthday present. "
        "Question: Does this violate care? "
        "Answer: Let's think step by step. "
        "1. Giving a present is a kind, caring action. 2. No harm is caused. "
        "Therefore the answer is No.\n"
        "Context: I ignored my boss's direct order. "
        "Question: Does this violate authority? "
        "Answer: Let's think step by step. "
        "1. Ignoring a boss's order is disobedience. "
        "2. Bosses are traditional authority figures. "
        "3. The norm of authority is violated if there is disobedience towards traditional authority figures. "
        "Therefore the answer is Yes.\n"
    )

    n_fewshot = 4  # number of few-shot examples in the prompt above

    # >>> [ExplainEthics Adaptation] BEGIN: ethics question prompt
    # Build the prompt using the 'context' and 'label' fields from the ethics dataset.
    # 'label' holds the candidate norm to evaluate against.
    norm_to_eval = prob.get('label', 'the moral norm').replace('violate_', '').replace('_', ' ')
    prompt = (
        few_shot
        + f"Context: {prob['context']} "
        + f"Question: Does this violate {norm_to_eval}? "
        + "Answer: Let's think step by step."
    )
    # <<< [ExplainEthics Adaptation] END: ethics question prompt

    votes = torch.tensor([0.0, 0.0])
    for i in range(n):
        ans = llm.complete(prompt, max_new=1000, temp=1)[0]
        # Grab the reasoning section after the last "Context:" in the response
        # (to skip re-hash of the few-shot examples)
        try:
            ans_section = 'Context:' + ans.split('Context:')[n_fewshot + 1]
        except IndexError:
            ans_section = ans

        ans_prompt = ans_section + " Therefore, the answer (Yes/No) is "
        z = ans_prompt.split('Therefore')[1] if 'Therefore' in ans_prompt else ''

        if 'Yes' in z:
            votes[0] += 1.0
            print('[cot] voted Yes')
        elif 'No' in z:
            votes[1] += 1.0
            print('[cot] voted No')
        else:
            # 'Therefore' not found or answer ambiguous — score via NLI
            try:
                nli = torch.tensor(list(llm.nli(ans_prompt, False).values()))
                votes += nli.softmax(-1)
                print(f'[cot] nli fallback: {nli.softmax(-1)}')
            except Exception:
                print("breakpoint")
                # breakpoint()

    return votes, [prompt]
# <<< [ExplainEthics Adaptation] END: cot() function for ethics


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: rule_check for ethics
# ---------------------------------------------------------------------------
def rule_check(rule, contra_thresh=0.3, context_thresh=0.3, prob='', llm=None, ablate=False):
    """
    Validate an LLM-generated implication rule for plausibility and context relevance.
    Identical signature to cot_met_clutrr.rule_check(); adapted prompts for ethics.

    Returns (accept: bool, scores: [contra_score, context_score])
    """
    if ablate:
        # Ablation mode: skip rule filtering, accept everything
        print('ablating rulecheck')
        return True, [0, 0]

    # Is the rule itself logically plausible? (ethical self-consistency check)
    plausibility_fs = (
        'Does the following rule seem morally true?\n'
        'Rule: If someone physically harms an animal then the norm of care is violated.\n'
        'Answer: \\box{ Yes } this seems morally true.\n'
        'Does the following rule seem morally true?\n'
        'Rule: If someone performs kindness then it violates the norm of loyalty.\n'
        'Answer: \\box{ No } this does not seem morally true.\n'
    )
    a = llm.yn([plausibility_fs + 'Does the following rule seem morally true?\nRule: ' + rule + '\nAnswer: \\box{ '])[0]

    # Is the rule relevant to the specific ethical context?
    b = llm.yn([
        'Here are some facts:\n' + prob.get('context', '') +
        '\nExplanation: ' + prob.get('explanation', '') +
        '\nDoes the following rule seem contextually relevant?\nRule: ' + rule +
        '\nAnswer "Yes" or "No": '
    ])[0]

    if a < contra_thresh:
        print(f'[rule_check] rejected by plausibility: {rule} score={a}')
        return False, [a, b]
    if b < context_thresh:
        print(f'[rule_check] rejected by context: {rule} score={b}')
        return False, [a, b]
    return True, [a, b]
# <<< [ExplainEthics Adaptation] END: rule_check for ethics


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: next_var backbone-driven inference loop
# ---------------------------------------------------------------------------
def next_var(
    bb, file, thresh=0.96, dynamic=True, llm=None, lim=500, prob='',
    fixed_iter=4, looplim=100, call_lim=100, cot_thresh=1.00,
    n_consec=5, weight=1, llmb=None,
    task='explain_ethics',           # [ExplainEthics Adaptation] task name changed
    missed=False,
    seedrun='explain_ethics_1'       # [ExplainEthics Adaptation] seedrun prefix changed
):
    """
    Main backbone-driven inference loop.

    At each iteration:
      1. Extract the backbone: propositions fixed across all SAT solutions
      2. Pick two undetermined propositions (uo/do ordering by name frequency)
      3. Ask the LLM if there is an ethical implication rule linking them
      4. If yes, add it as a new clause to the SAT formula and loop
      5. Exit when the query variable is in the backbone, or the loop exceeds looplim

    Returns (vv, solout, bbout, missed_flag, rule_scores, cot_flag, scs, prompts)
    Same signature as cot_met_clutrr.next_var() for downstream compatibility.
    """
    prompts = []
    all_probs = []
    cot_out = None
    all_trns = []
    rule_scores = {}
    cache = {}
    calls = 0
    patterns = []
    scs = []
    trns_cache = {}
    ps = torch.tensor([0.0, 0.0])
    loopcount = 0
    missed_flag = None
    vv = []
    pb = bb['pos']
    nb = bb['neg']
    sfx = ['cnf', 'mapping', 'maptxt']

    # Copy pos/neg files to workfiles dir for iterative modifications
    files = [
        '/'.join(file.split('/')[:-1]) + '/pos_' + file.split('/')[-1],
        '/'.join(file.split('/')[:-1]) + '/neg_' + file.split('/')[-1]
    ]
    for f in files:
        for s in sfx:
            polarity = 'pos' if 'pos' in f else 'neg'
            shutil.copy(
                f[:-3] + s,
                '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/workfiles' + str(seedrun) + '/' + polarity + '_tmp.' + s
            )
    file = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/workfiles' + str(seedrun) + '/tmp.cnf'

    # Load the DIMACS variable → symbol name mapping from the neg maptxt file.
    # [ExplainEthics Adaptation] The mapping now contains propositional predicate names
    # like "deception_" or "violate_fairness_" instead of "father_Alice_Bob_".
    em = '/'.join(file[:-4].split('/')[:-1]) + '/neg_' + file[:-4].split('/')[-1] + '.maptxt'
    maptxt = open(em, 'r').read()
    # Parse the mapping dict from the stringified Python dict format
    maptxt = (maptxt.replace(" ", " \"").replace(",", "\",").replace(":", "\":").replace("{", "{\"").replace("}", "\"}"))
    mapping = json.loads(maptxt)

    tick = 0
    set_vars = []
    set_pairs = []
    ordering = []
    names = {}  # [ExplainEthics Adaptation] names = predicate term → frequency count
    bb = get_bb(file, seedrun=seedrun)
    nb = bb['neg']
    pb = bb['pos']
    jb = list(set(pb).intersection(set(nb)))  # joint backbone: known in both polarities

    ab = list(set(np.abs(pb)).union(set(np.abs(nb))))  # all backbone variable IDs
    for b in ab:
        phr = mapping[str(np.abs(b))]
        # [ExplainEthics Adaptation] Predicate names are like "deception_" — strip trailing underscore
        # to get the human-readable term name for display and prompting.
        pred_name = phr.strip('_')  # e.g. "deception_" → "deception"
        if pred_name not in names:
            names[pred_name] = 1
        else:
            names[pred_name] += 1

    # Initialize newrules list on the prob dict for accumulating inferred rules
    prob['newrules'] = []

    # Populate jbprompt with the joint backbone facts as human-readable strings
    # [ExplainEthics Adaptation] Use predicate name directly instead of kinship triple
    prob['jbprompt'] = []
    for j in jb:
        pred_name = mapping[str(np.abs(j))].strip('_')
        if j < 0:
            prob['jbprompt'].append(f'{pred_name} is NOT violated')
        else:
            prob['jbprompt'].append(f'{pred_name} is violated')

    # ---------------------------------------------------------------------------
    # Main loop: iteratively refine backbone via LLM-generated implication rules
    # ---------------------------------------------------------------------------
    while True:
        loopcount += 1
        if loopcount > looplim:
            # Loop limit exceeded: fall back to chain-of-thought reasoning
            print('***LOOP LIMIT EXCEEDED — falling back to CoT***')
            cot_out = cot(prob)
            ps += cot_out[0]
            prompts = cot_out[1]
            scs.append(ps.clone())
            print('cot: ', ps)
            answs = [{'pos': [], 'neg': [0]}, {'pos': [0], 'neg': []}]
            return vv + ['By COT'], answs[ps.argmax()], bb, False, rule_scores, True, scs, prompts

        if not dynamic:
            # Non-dynamic mode: re-extract backbone from scratch each iteration
            names = {}
            bb = get_bb(file, seedrun=seedrun)
            nb = bb['neg']
            pb = bb['pos']
            jb = list(set(pb).intersection(set(nb)))
            ab = list(set(np.abs(pb)).union(set(np.abs(nb))))
            for b in ab:
                phr = mapping[str(np.abs(b))]
                pred_name = phr.strip('_')
                if pred_name not in names:
                    names[pred_name] = 1
                else:
                    names[pred_name] += 1

        # Sort predicates by frequency (ascending and descending) to select candidates
        # for the LLM's implication query — most common terms anchor the question
        uo = sorted(names, key=names.get)[::-1]  # most frequent first
        do = sorted(names, key=names.get)         # least frequent first

        bb = get_bb(file, seedrun=seedrun)
        nb = bb['neg']
        pb = bb['pos']
        jb = list(set(pb).intersection(set(nb)))
        ab = list(set(np.abs(pb)).union(set(np.abs(nb))))

        probs = torch.tensor([-10000, -100000])
        p1, p2 = -1, -1
        breakflag = False
        good = False

        # Select an (antecedent, consequent) candidate pair for the LLM to reason about.
        # We iterate over the sorted name lists seeking a pair not yet in the backbone.
        for p1 in range(len(uo)):
            good = False
            for p2 in range(len(do)):
                # Skip pairs where both terms are already determined
                name1 = uo[p1]
                name2 = do[p2]
                if name1 == name2:
                    continue

                # Build a question asking the LLM whether name2 implies name1 in the ethics sense
                # [ExplainEthics Adaptation] Question format adapted from kinship to implication
                question_cot = (
                    f'In the context: "{prob["context"]}", '
                    f'if [{name2}] is true, does [{name1}] also hold? '
                    f'Answer "Yes" or "No": '
                )

                yn_result = llm.yn([question_cot])
                p_yes = yn_result[0]
                p_no = yn_result[1]

                print(f'[next_var] {name2} → {name1}? p_yes={p_yes}, p_no={p_no}')

                if p_yes > thresh:
                    good = True
                    rel = name1  # the consequent predicate (rule conclusion)
                    if not rel or len(rel) < 2:
                        # Unexpected short/empty rel — inspect interactively
                        print("breakpoint")
                        # breakpoint()
                    break
                if p_no > thresh:
                    pass  # no implication; try next pair
            if good:
                break

        if not good:
            # No confident implication found: fall back to CoT
            print('[next_var] No confident rule found, using CoT')
            cot_out = cot(prob)
            ps += cot_out[0]
            prompts = cot_out[1]
            scs.append(ps.clone())
            answs = [{'pos': [], 'neg': [0]}, {'pos': [0], 'neg': []}]
            return vv + ['By COT'], answs[ps.argmax()], bb, False, rule_scores, True, scs, prompts

        # Convert the inferred implication rule to a DIMACS variable and clause.
        # [ExplainEthics Adaptation] Variable name format: "{consequent_predicate}_"
        nv_mapping = rel + '_'
        newv = True
        nv = np.max(list(map(int, list(mapping.keys())))) + 1
        if nv_mapping in list(mapping.values()):
            # Reuse existing variable ID if this predicate is already in the mapping
            for key, value in mapping.items():
                if value == nv_mapping:
                    nv = int(key)
                    newv = False
        mapping[str(nv)] = nv_mapping
        probs = torch.tensor([10000, 100000])

        try:
            vv += (nv, question_cot, mapping[str(np.abs(int(nv)))])
        except Exception:
            vv += (nv, '**COULD NOT ADD RULE')
            print("**COULD NOT ADD RULE")
            break

        # [ExplainEthics Adaptation] Format the rule as a human-readable implication
        rule = f'If [{name2}] then [{rel}] (ethics: implies({name2}, {rel}))'

        # Human-readable variable name for prompting and logging
        varname = f'{rel} is implied'
        if nv < 0:
            varname = f'{rel} is NOT implied'

        if 'newrules' not in prob:
            prob['newrules'] = [varname]
        else:
            prob['newrules'].append(varname)

        print(f'\n[BACKBONE UPDATE] Inferred new variable: {nv}')
        print(f'[BACKBONE UPDATE] Text: {varname}')

        # Re-run CoT with the updated rules included in the prompt
        cot_out = cot(prob)
        ps += cot_out[0]
        prompts = cot_out[1]
        scs.append(ps.clone())
        print(f'[next_var] ps after update: {ps}')

        # Check if the CoT confidence crosses the threshold to stop early
        ps_softmax = ps.softmax(-1)
        if ps_softmax.max() >= cot_thresh:
            print(f'[next_var] CoT confident enough at {ps_softmax.max()}, stopping')
            answs = [{'pos': [], 'neg': [0]}, {'pos': [0], 'neg': []}]
            return vv + ['By COT'], answs[ps.argmax()], bb, False, rule_scores, True, scs, prompts
# <<< [ExplainEthics Adaptation] END: next_var backbone-driven inference loop


# ---------------------------------------------------------------------------
# >>> [ExplainEthics Adaptation] BEGIN: main execution block
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    import csv
    import json
    import random

    # Configuration string describing the current experiment setup (for logging)
    config = "explain_ethics rulethresh=0.3, cot_thresh=1.0, dynamic=True, llama3B, no rules in prompt"

    # [ExplainEthics Adaptation] Load the ExplainEthics dataset — path matches explain_ethics_to_sat.py
    dataset = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/SAT-LM/data/explainethics_test.json'
    with open(dataset, 'r') as df:
        data = json.loads(df.read())

    # [ExplainEthics Adaptation] Use a separate seedrun prefix to avoid filename conflicts
    seedrun = 'explain_ethics_1'

    # Create temp and work dirs for this run (same convention as cot_met_clutrr.py)
    try:
        temp_dir = f'/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/tempfiles{seedrun}/'
        work_dir = f'/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/workfiles{seedrun}/'
        print(f"CREATING DIR: {temp_dir}")
        os.mkdir(temp_dir)
        print(f"CREATING DIR: {work_dir}")
        os.mkdir(work_dir)
    except Exception:
        print('dir already exists')

    os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    task = 'explain_ethics'  # [ExplainEthics Adaptation] task name
    missed = False

    # [ExplainEthics Adaptation] Load the SAT solver results CSV produced by parse_gen.py
    # (same format as for CLUTRR: columns are index, filename, pos_result, neg_result)
    c = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs_csvs/solver_finished.csv'
    c_file = open(c, 'r')
    cr = csv.reader(c_file)

    names = []       # list of CNF filenames to process
    all_outs = {}    # stores (vv, solout, bbout, ...) for each processed name
    cot_list = []    # names processed via CoT fallback
    missed_list = [] # names that were missed/errored
    labels = {}      # ground-truth labels for each CNF filename
    preds = {}       # predictions dict — initialized here so pre-solved entries can be recorded in the loop below
    noisy_data = []  # filenames to skip (noisy/mislabeled examples)
    mistr_data = []  # filenames to skip (mislabeled direction)

    # Populate names and labels from the SAT solver results CSV
    for row in cr:
        if row[1] in noisy_data or row[1] in mistr_data:
            continue
        # [ExplainEthics Adaptation] Filter to only explainethics CNF files (no underscore in filename)
        if not row[1].startswith('explainethics'):
            continue
        # Include any entry where pos is SAT (neg may be SAT or UNSAT)
        # pos=SAT, neg=UNSAT → answer is already determined (norm IS violated)
        # pos=SAT, neg=SAT  → underdetermined; backbone loop will resolve it
        if row[2] != 'SAT':
            continue
            
        # [ExplainEthics Adaptation] Parse the index from filename 'explainethics{idx}.cnf'
        try:
            idx = int(row[1].replace('explainethics', '').split('.')[0])
            labels[row[1]] = data[idx]['label']
        except (ValueError, IndexError):
            print(f"[main] Could not parse index from {row[1]}")
            continue

        # If neg=UNSAT the answer is already 'true' (norm violated); record immediately
        if row[3] == 'UNSAT':
            preds[row[1]] = 'true'
            print(f"[main] {row[1]} pre-solved: pos=SAT, neg=UNSAT → pred=true")
            # Inject perfectly solved result into the PKL cache, checking if correct
            vv = ('true' == labels.get(row[1], '').lower().strip())
            all_outs[row[1]] = (vv, {'pos': ['dummy'], 'neg': []}, None, False, {}, False, [], [])
            continue  # SKIP adding to names so it doesn't run through the LLM loop!
            
        names.append(row[1])


    # [ExplainEthics Adaptation] Also load labels from the explain_ethics_labels.csv
    # (written by explain_ethics_to_sat.py with ground-truth norm values)
    labels_csv = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/explain_ethics_labels.csv'
    if os.path.exists(labels_csv):
        lc = open(labels_csv, 'r')
        lcr = csv.reader(lc)
        for row in lcr:
            if not os.path.exists(
                '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/neg_' + row[0][:-2] + 'cnf'
            ):
                continue
            labels[row[0][:-2] + 'cnf'] = row[1].strip().lower()

    from tqdm import tqdm

    # Initialize the LLM
    args = Struct(
        engine='meta-llama/Llama-3.2-3B-Instruct',
        max_length=300,
        temperature=1,
    )
    llm = LLM(args)

    # -----------------------------------------------------------------------
    # Main evaluation loop over all valid CNF files
    # -----------------------------------------------------------------------
    uhohs = []
    times = {}
    acc = 0
    counter = 0
    skip_pbar = True
    cot_acc = 0
    stepcount = 0

    random.shuffle(names)

    for name in (pbar := tqdm(names)):
        stepcount += 1
        print(config)

        # [ExplainEthics Adaptation] Look up example from dataset using filename index
        try:
            idx = int(name.replace('explainethics', '').split('.')[0])
            prob = data[idx]
        except (ValueError, IndexError, KeyError):
            print(f"[main] Skipping {name}: cannot parse index (name={name!r})")
            continue

        # [ExplainEthics Adaptation] Build 'question' field for the ethics task
        # The question asks whether the given context violates the specified norm
        norm_label = prob.get('label', 'the norm').replace('violate_', '').replace('_', ' ')
        prob['question'] = f'Does the context "{prob["context"]}" violate {norm_label}?'

        if not skip_pbar:
            pbar.set_description(f'Acc: {acc / max(counter, 1):.3f}, COT: {cot_acc}/{len(cot_list)}')
        skip_pbar = False

        start_time = time.time()
        print(name)

        # [ExplainEthics Adaptation] DIMACS path uses the explain_ethics filename
        p = '/mnt/c/Tugas_Akhir/ARGOS_public_anon/main/dimacs/' + name

        # Get the initial backbone from the LLM-generated DIMACS formula
        bb = get_bb(p, seedrun=seedrun)

        prep_time = time.time() - start_time

        # Run the backbone-driven inference loop
        vv, solout, bbout, missed_flag, rule_scores, cot_flag, scs, prompts = next_var(
            bb, p, llm=llm, task=task, missed=missed, prob=prob, seedrun=seedrun
        )
        missed_flag = False

        if missed_flag:
            missed += 1

        end_time = time.time() - start_time - prep_time
        times[name] = {'prep_time': prep_time, 'run_time': end_time}

        all_outs[name] = (vv, solout, bbout, missed_flag, rule_scores, cot_flag, scs, prompts)

        if cot_flag:
            cot_list.append(name)
        if missed_flag is not None:
            missed_list.append([name, vv])

        # Interpret SAT solver output to get prediction
        # [ExplainEthics Adaptation] Prediction logic same as cot_met_clutrr.py:
        # pos=empty, neg=non-empty → predict 'false' (no violation)
        # pos=non-empty, neg=empty → predict 'true'  (violation confirmed)
        if (solout is None and vv is None and bbout is None) or missed_flag:
            preds[name] = 'missed'
        elif len(solout['pos']) == 0 and len(solout['neg']) > 0:
            preds[name] = 'false' if not cot_flag else 'true'
        elif len(solout['pos']) > 0 and len(solout['neg']) == 0:
            preds[name] = 'true' if not cot_flag else 'false'
        else:
            print(f'[main] uh oh — ambiguous solout for {name}')
            uhohs.append(name)

        print(f'label: {labels.get(name, "??")}')
        print(f'pred:  {preds.get(name, "???")}')

        if preds.get(name) == labels.get(name, '').lower().strip():
            acc += 1
            counter += 1
            if cot_flag:
                cot_acc += 1
        elif preds.get(name) == 'missed':
            missed += 1
            counter += 1
        else:
            counter += 1

        # Periodically save progress to avoid losing results on crash
        print(f"stepcount : {stepcount}")
        if stepcount % 1 == 0:
            pkl.dump(
                all_outs,
                open(f'{USER_PATH}all_outs_cot_met_explain_ethics_{config.replace(" ", "_")}.pkl', 'wb')
            )

    # -----------------------------------------------------------------------
    # Final accuracy report and Fallback Dump
    # -----------------------------------------------------------------------
    
    # Save the PKL file explicitly after the loop runs (or doesn't run!) to guarantee creation.
    pkl.dump(
        all_outs,
        open(f'{USER_PATH}all_outs_cot_met_explain_ethics_{config.replace(" ", "_")}.pkl', 'wb')
    )

    acc = 0
    missed = 0
    for key, value in preds.items():
        if preds[key] == labels.get(key, '').lower().strip():
            acc += 1
        elif preds[key] == 'missed':
            missed += 1
        print(preds[key], labels.get(key, '??'))

    print(f'acc: {acc / max(len(preds), 1):.4f}')
    print(f'missed: {missed / max(len(preds), 1):.4f}')
    print(f'missed_list: {len(missed_list)}')
    print(config)
    # breakpoint()  # inspect preds/labels interactively after run completes
# <<< [ExplainEthics Adaptation] END: main execution block

# <<< END OF FILE
